// @ts-nocheck
(function () {
  "use strict";

  const HG_PUBLIC_PROFILES = "hg_public_profiles_v1";
  const CURRENT_PROFILE_KEY = "hg_public_profile_v1";
  const INVITES_KEY = "hg_knowledge_meet_invites_v1";
  const HG_SOCIAL_LOG = "hg_social_log_v1";
  const PRESETS = Object.freeze([
    "Vil du utforske dette stedet sammen?",
    "Vil du ta denne ruta sammen?",
    "Vil du ta quizen her sammen?",
    "Vil du sammenligne observasjoner her?"
  ]);
  const VALID_STATUSES = new Set(["pending", "accepted", "declined", "confirmed", "cancelled"]);

  const MOCK_PROFILES = Object.freeze([
    { userId: "mock-saga", displayName: "Saga", publicProfile: true, bio: "Liker byhistorie, arkitektur og små spor i gatene.", avatar: "", badges: ["historie", "by"], completedEmner: ["oslo", "arkitektur"], coreConcepts: ["urbanisering", "offentlighet", "modernisme"], interests: ["by", "politikk"] },
    { userId: "mock-ask", displayName: "Ask", publicProfile: true, bio: "Samler på natur- og vitenskapsspor i History Go.", avatar: "", badges: ["natur", "vitenskap"], completedEmner: ["biologi", "oslo"], coreConcepts: ["økologi", "observasjon", "klassifikasjon"], interests: ["natur", "vitenskap"] },
    { userId: "mock-ida", displayName: "Ida", publicProfile: true, bio: "Kunst, litteratur og idehistorie sett gjennom steder.", avatar: "", badges: ["kunst", "litteratur", "historie"], completedEmner: ["modernisme", "oslo"], coreConcepts: ["modernisme", "kanon", "offentlighet"], interests: ["kunst", "litteratur"] }
  ]);

  function readJson(key, fallback) { try { return JSON.parse(localStorage.getItem(key) || "") || fallback; } catch { return fallback; } }
  function writeJson(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
  function cleanList(value) { return Array.from(new Set((Array.isArray(value) ? value : []).map((item) => String(item || "").trim()).filter(Boolean))); }
  function escapeHtml(s) { return String(s ?? "").replace(/[&<>\"']/g, (ch) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "\"":"&quot;", "'":"&#039;" }[ch])); }
  function getCurrentUserId() { return String(window.HGAha?.getProfileIdSync?.() || localStorage.getItem("aha_profile_id") || "local-user"); }
  function getDisplayName() { const name = window.HGUserProfile?.getDisplayName?.() || localStorage.getItem("user_name") || "History Go bruker"; return name === "Logg inn" ? "History Go bruker" : name; }
  function addWeight(vector, key, weight) { const id = String(key || "").trim(); if (id) vector[id] = Number(vector[id] || 0) + Number(weight || 0); }
  function badgeTierWeight(value) { const n = Number(value?.tier || value?.level || value?.points || value?.count || 1); return Math.max(1, Math.min(12, n)); }
  function guardSocialPayload(payload, context) { window.HG_SocialGuards?.assertNoSocialPrivacyLeak?.(payload, context); return payload; }

  function normalizeProfile(profile) {
    return {
      userId: String(profile?.userId || "").trim(),
      displayName: String(profile?.displayName || "History Go bruker"),
      publicProfile: profile?.publicProfile === true,
      bio: String(profile?.bio || ""),
      avatar: String(profile?.avatar || profile?.avatarUrl || ""),
      badges: cleanList(profile?.badges),
      completedEmner: cleanList(profile?.completedEmner),
      coreConcepts: cleanList(profile?.coreConcepts),
      interests: cleanList(profile?.interests)
    };
  }

  function deriveCurrentSignals(profile) {
    const quizProgress = readJson("quiz_progress", {});
    Object.entries(quizProgress || {}).forEach(([badgeId, progress]) => {
      const completed = cleanList(progress?.completed);
      if (completed.length) profile.badges.push(badgeId);
      completed.forEach((quizId) => profile.coreConcepts.push(quizId));
    });
    const history = window.HGLearningLog?.getQuizHistory?.() || readJson("hg_learning_log_v1", []);
    (Array.isArray(history) ? history : []).forEach((entry) => {
      [entry?.concept, entry?.topic, entry?.id, entry?.targetId].forEach((v) => v && profile.coreConcepts.push(v));
      [entry?.category, entry?.domain, entry?.badgeId].forEach((v) => v && profile.interests.push(v));
    });
    profile.badges = cleanList(profile.badges); profile.completedEmner = cleanList(profile.completedEmner); profile.coreConcepts = cleanList(profile.coreConcepts); profile.interests = cleanList(profile.interests);
    return profile;
  }

  function getCurrentPublicProfile() {
    const stored = readJson(CURRENT_PROFILE_KEY, {});
    return guardSocialPayload(deriveCurrentSignals(normalizeProfile({ userId: getCurrentUserId(), displayName: stored.displayName || getDisplayName(), publicProfile: Boolean(stored.publicProfile), bio: stored.bio, avatar: stored.avatar, badges: stored.badges, completedEmner: stored.completedEmner, coreConcepts: stored.coreConcepts, interests: stored.interests })), "publicProfile");
  }

  function getAllProfiles() {
    const saved = readJson(HG_PUBLIC_PROFILES, []);
    const merged = [...MOCK_PROFILES, ...(Array.isArray(saved) ? saved : []), getCurrentPublicProfile()].map(normalizeProfile);
    const byId = new Map(); merged.forEach((p) => { if (p.userId) byId.set(p.userId, { ...(byId.get(p.userId) || {}), ...p }); });
    return guardSocialPayload(Array.from(byId.values()), "publicProfile");
  }

  function savePublicProfile(patch) {
    const next = normalizeProfile({ ...getCurrentPublicProfile(), ...(patch || {}) });
    const privacy = window.getPrivacySettings?.(next.userId);
    next.publicProfile = Boolean((patch && Object.prototype.hasOwnProperty.call(patch, "publicProfile")) ? patch.publicProfile : (privacy?.publicProfile ?? next.publicProfile));
    writeJson(CURRENT_PROFILE_KEY, next);
    const others = getAllProfiles().filter((p) => p.userId !== next.userId && !String(p.userId).startsWith("mock-"));
    writeJson(HG_PUBLIC_PROFILES, [...others, next]);
    window.HG_PUBLIC_PROFILE = next;
    renderKnowledgeMatches(); renderMeetInviteInbox(); renderConfirmedMeets(); renderSocialTimeline(); renderSocialProgression(); renderLearningCircles();
    return next;
  }
  function togglePublicProfile(force) { const current = getCurrentPublicProfile(); return savePublicProfile({ publicProfile: typeof force === "boolean" ? force : !current.publicProfile }); }

  function buildKnowledgeFingerprint(profile) {
    const p = profile ? normalizeProfile(profile) : getCurrentPublicProfile();
    const conceptVector = {}, domainVector = {}, badgeVector = {}, emneVector = {};
    p.coreConcepts.forEach((id) => addWeight(conceptVector, id, 3));
    p.interests.forEach((id) => addWeight(domainVector, id, 2));
    p.completedEmner.forEach((id) => { addWeight(emneVector, id, 4); addWeight(domainVector, id, 1.5); });
    p.badges.forEach((id) => addWeight(badgeVector, id, 3));
    if (!profile || p.userId === getCurrentUserId()) {
      const quizProgress = readJson("quiz_progress", {});
      Object.entries(quizProgress || {}).forEach(([badgeId, progress]) => { const completed = cleanList(progress?.completed); addWeight(badgeVector, badgeId, 2 + completed.length); completed.forEach((quizId) => addWeight(conceptVector, quizId, 1.5)); });
      Object.entries(readJson("merits_by_category", {}) || {}).forEach(([badgeId, merit]) => addWeight(badgeVector, badgeId, badgeTierWeight(merit)));
      (window.HGLearningLog?.getQuizHistory?.() || readJson("hg_learning_log_v1", []) || []).forEach((entry) => { addWeight(conceptVector, entry?.concept || entry?.topic || entry?.id || entry?.targetId, entry?.correct === false ? 0.5 : 2); addWeight(domainVector, entry?.category || entry?.domain || entry?.badgeId, 1.5); addWeight(badgeVector, entry?.badgeId || entry?.category, 1); });
    }
    return { conceptVector, domainVector, badgeVector, emneVector };
  }
  function dotSimilarity(a, b) { const keys = new Set([...Object.keys(a || {}), ...Object.keys(b || {})]); let dot = 0, ma = 0, mb = 0; keys.forEach((k) => { const av = Number(a?.[k] || 0), bv = Number(b?.[k] || 0); dot += av * bv; ma += av * av; mb += bv * bv; }); return ma && mb ? dot / (Math.sqrt(ma) * Math.sqrt(mb)) : 0; }
  function shared(a, b, key) { return cleanList(a?.[key]).filter((id) => cleanList(b?.[key]).includes(id)); }
  function calculateMatchScore(userA, userB) { const fa = buildKnowledgeFingerprint(userA), fb = buildKnowledgeFingerprint(userB); return Math.round(Math.min(100, (dotSimilarity(fa.conceptVector, fb.conceptVector) * 35) + (dotSimilarity(fa.domainVector, fb.domainVector) * 25) + (dotSimilarity(fa.badgeVector, fb.badgeVector) * 20) + (dotSimilarity(fa.emneVector, fb.emneVector) * 20))); }
  function getKnowledgeMatches(userId) { const current = getAllProfiles().find((p) => p.userId === String(userId || getCurrentUserId())) || getCurrentPublicProfile(); if (!current.publicProfile || window.getPrivacySettings?.(current.userId)?.visibleInMatchLists === false) return []; const matches = getAllProfiles().filter((p) => p.publicProfile && p.userId !== current.userId && (window.canSeeMatch ? window.canSeeMatch(current.userId, p.userId) : true)).map((target) => { const sharedConcepts = shared(current, target, "coreConcepts"), sharedBadges = shared(current, target, "badges"), sharedEmner = shared(current, target, "completedEmner"); const matchScore = calculateMatchScore(current, target); const reasonText = sharedConcepts.length ? `Deler ${sharedConcepts.length} kjernebegrep` : sharedEmner.length ? `Deler ${sharedEmner.length} emner` : sharedBadges.length ? `Deler ${sharedBadges.length} merker` : "Lignende kunnskapsdomener"; return { targetUserId: target.userId, displayName: target.displayName, avatar: target.avatar, matchScore, sharedConcepts, sharedBadges, sharedEmner, reasonText }; }).filter((m) => m.matchScore > 0).sort((a, b) => b.matchScore - a.matchScore); return guardSocialPayload(matches, "knowledgeMatch"); }
  function updateKnowledgeFingerprint(context = {}) { const fp = buildKnowledgeFingerprint(getCurrentPublicProfile()); writeJson("hg_knowledge_fingerprint_v1", { userId: getCurrentUserId(), updatedAt: new Date().toISOString(), context, fingerprint: fp }); return fp; }
  function updateSocialMatchIndex(context = {}) { const matches = getKnowledgeMatches(getCurrentUserId()); writeJson("hg_social_match_index_v1", { userId: getCurrentUserId(), updatedAt: new Date().toISOString(), context, matches }); renderKnowledgeMatches(); return matches; }
  function checkSharedQuizOpportunities(quizId = "", context = {}) { const top = getKnowledgeMatches(getCurrentUserId()).filter((m) => Number(m.matchScore || 0) >= 35).slice(0, 3); const rows = top.map((m) => ({ opportunityId: `quiz-opp-${quizId || "any"}-${m.targetUserId}`, quizId: String(quizId || ""), targetUserId: m.targetUserId, matchScore: m.matchScore, categoryId: String(context.categoryId || ""), createdAt: new Date().toISOString() })); writeJson("hg_shared_quiz_opportunities_v1", rows); return rows; }
  function updateTrustFromSharedCompletion(kind, participants = [], itemId = "") { const log = getSocialLog(); cleanList(participants).filter((id) => id !== getCurrentUserId()).forEach((id) => { const patch = {}; if (kind === "route") patch.sharedRoutes = [itemId]; if (kind === "quiz") patch.sharedQuizzes = [itemId]; if (kind === "observation") patch.sharedObservations = [itemId]; if (kind === "meet") patch.repeatedMeetCount = Number((getSocialRelations(log).find((r) => r.userId === id) || {}).repeatedMeetCount || 0) + 1; upsertRelation(log, id, patch); }); writeJson(HG_SOCIAL_LOG, log); return log; }
  function addSocialTimelineEvent(type, data = {}) { const rows = readJson("hg_social_timeline_v1", []); const event = { eventId: `social-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, type: String(type || "activity"), private: true, createdAt: new Date().toISOString(), ...data }; writeJson("hg_social_timeline_v1", [...(Array.isArray(rows) ? rows : []), event]); renderSocialTimeline(); return event; }
  function awardSocialLearningBadge(badgeId) { const id = String(badgeId || ""); if (!id) return null; const state = readJson("hg_social_learning_badges_v1", {}); state[id] = { badgeId: id, unlockedAt: state[id]?.unlockedAt || new Date().toISOString() }; writeJson("hg_social_learning_badges_v1", state); return state[id]; }
  function getProfileByUserId(userId) { return getAllProfiles().find((p) => p.userId === String(userId || "")) || null; }
  function initials(name) { return String(name || "HG").trim().split(/\s+/).slice(0, 2).map((p) => p[0]?.toUpperCase()).join("") || "HG"; }
  function chips(items, empty) { const list = cleanList(items); return list.length ? `<div class="match-profile-chips">${list.map((i) => `<span>${escapeHtml(i)}</span>`).join("")}</div>` : `<p class="match-profile-empty">${escapeHtml(empty)}</p>`; }
  function avatarHtml(profile, cls = "match-profile-avatar") { return profile.avatar ? `<img class="${cls}" src="${escapeHtml(profile.avatar)}" alt="">` : `<div class="${cls} match-profile-avatar-fallback" aria-hidden="true">${escapeHtml(initials(profile.displayName))}</div>`; }

  function renderMatchProfile(profile) { const match = getKnowledgeMatches(getCurrentUserId()).find((m) => m.targetUserId === profile.userId) || { sharedConcepts: [], sharedBadges: [], sharedEmner: [], reasonText: "Lignende kunnskapsdomener" }; return `<div class="hg-modal match-profile-modal"><header class="hg-modal-header match-profile-header">${avatarHtml(profile)}<div><p class="hg-modal-meta">Offentlig kunnskapsprofil</p><h2 class="hg-modal-title">${escapeHtml(profile.displayName)}</h2><p class="match-profile-bio">${escapeHtml(profile.bio || "Offentlig profil i History Go.")}</p></div></header><div class="hg-modal-body match-profile-body"><section class="hg-section match-profile-section"><h3>Læringsidentitet</h3><div class="match-profile-grid"><div><h4>Badges</h4>${chips(profile.badges, "Ingen badges.")}</div><div><h4>Fullførte emner</h4>${chips(profile.completedEmner, "Ingen emner.")}</div><div><h4>Kjernebegrep</h4>${chips(profile.coreConcepts, "Ingen begrep.")}</div><div><h4>Interesser</h4>${chips(profile.interests, "Ingen interesser.")}</div></div></section><section class="hg-section match-profile-section"><h3>Felles lag</h3><div class="match-profile-grid"><div><h4>Delte begrep</h4>${chips(match.sharedConcepts, "Ingen delte begrep.")}</div><div><h4>Delte badges</h4>${chips(match.sharedBadges, "Ingen delte badges.")}</div><div><h4>Delte emner</h4>${chips(match.sharedEmner, "Ingen delte emner.")}</div><div><h4>Matchgrunn</h4><p>${escapeHtml(match.reasonText)}</p></div></div></section><div class="match-profile-actions"><button type="button" data-match-action="meet">Foreslå møte</button><button type="button" data-match-action="close">Lukk</button></div></div></div>`; }
  function closeMatchProfilePopup() { document.getElementById("matchProfilePopup")?.remove(); }
  function openMatchProfile(userId) { const profile = getProfileByUserId(userId); if (!profile?.publicProfile || (window.canSeeProfile && !window.canSeeProfile(getCurrentUserId(), userId))) return null; closeMatchProfilePopup(); const popup = document.createElement("div"); popup.id = "matchProfilePopup"; popup.className = "hg-popup match-profile-popup"; popup.setAttribute("role", "dialog"); popup.setAttribute("aria-modal", "true"); popup.innerHTML = `<div class="hg-popup-inner">${renderMatchProfile(profile)}</div>`; popup.addEventListener("click", (event) => { if (event.target === popup) closeMatchProfilePopup(); const action = event.target?.closest?.("[data-match-action]")?.getAttribute("data-match-action"); if (action === "close") closeMatchProfilePopup(); if (action === "meet") { closeMatchProfilePopup(); openMeetInviteModal(profile.userId); } }); document.body.appendChild(popup); return popup; }

  function getSocialLog() { const log = readJson(HG_SOCIAL_LOG, {}); return { userId: String(log.userId || getCurrentUserId()), metUsers: cleanList(log.metUsers), metAtSpots: cleanList(log.metAtSpots), sharedQuizzes: cleanList(log.sharedQuizzes), sharedRoutes: cleanList(log.sharedRoutes), sharedObservations: cleanList(log.sharedObservations), repeatedMeetCount: Number(log.repeatedMeetCount || 0), relations: Array.isArray(log.relations) ? log.relations : [], acceptedInvites: cleanList(log.acceptedInvites), declinedInvites: cleanList(log.declinedInvites), completedMeetups: cleanList(log.completedMeetups) }; }
  function saveSocialLog(log) { writeJson(HG_SOCIAL_LOG, getSocialLogFromPatch(log)); }
  function getSocialLogFromPatch(patch) { const base = getSocialLog(); return { ...base, metUsers: cleanList([...(base.metUsers || []), ...cleanList(patch?.metUsers)]), metAtSpots: cleanList([...(base.metAtSpots || []), ...cleanList(patch?.metAtSpots)]), sharedQuizzes: cleanList([...(base.sharedQuizzes || []), ...cleanList(patch?.sharedQuizzes)]), sharedRoutes: cleanList([...(base.sharedRoutes || []), ...cleanList(patch?.sharedRoutes)]), sharedObservations: cleanList([...(base.sharedObservations || []), ...cleanList(patch?.sharedObservations)]), repeatedMeetCount: Math.max(Number(base.repeatedMeetCount || 0), Number(patch?.repeatedMeetCount || 0)), relations: Array.isArray(patch?.relations) ? patch.relations : base.relations, acceptedInvites: cleanList([...(base.acceptedInvites || []), ...cleanList(patch?.acceptedInvites)]), declinedInvites: cleanList([...(base.declinedInvites || []), ...cleanList(patch?.declinedInvites)]), completedMeetups: cleanList([...(base.completedMeetups || []), ...cleanList(patch?.completedMeetups)]) }; }
  function getMeetInvites() { return (Array.isArray(readJson(INVITES_KEY, [])) ? readJson(INVITES_KEY, []) : []).map((i) => ({ inviteId: String(i?.inviteId || ""), fromUserId: String(i?.fromUserId || ""), toUserId: String(i?.toUserId || ""), spotId: String(i?.spotId || ""), proposedTime: String(i?.proposedTime || ""), messagePreset: PRESETS.includes(i?.messagePreset) ? i.messagePreset : PRESETS[0], status: VALID_STATUSES.has(i?.status) ? i.status : "pending", fromDisplayName: String(i?.fromDisplayName || ""), toDisplayName: String(i?.toDisplayName || ""), spotTitle: String(i?.spotTitle || "") })).filter((i) => i.inviteId && i.fromUserId && i.toUserId); }
  function saveMeetInvites(invites) { writeJson(INVITES_KEY, Array.isArray(invites) ? invites : []); renderMeetInviteInbox(); renderConfirmedMeets(); renderSocialTimeline(); renderSocialProgression(); renderLearningCircles(); }
  function getSpotTitle(invite) { const id = String(invite?.spotId || ""); const place = (Array.isArray(window.PLACES) ? window.PLACES : []).find((p) => String(p?.id || p?.placeId || "") === id); return invite?.spotTitle || place?.title || place?.name || id || "Valgt sted"; }
  function sendMeetInvite(toUserId, spotId = "", options = {}) { if ((window.canSendInvite && !window.canSendInvite(getCurrentUserId(), toUserId)) || (window.canInteract && !window.canInteract(getCurrentUserId(), toUserId))) return null; const target = getProfileByUserId(toUserId); const invite = { inviteId: `hg-invite-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, fromUserId: getCurrentUserId(), toUserId: String(toUserId || ""), spotId: String(spotId || ""), proposedTime: String(options.proposedTime || ""), messagePreset: PRESETS.includes(options.messagePreset) ? options.messagePreset : PRESETS[0], status: "pending", fromDisplayName: getDisplayName(), toDisplayName: target?.displayName || "", spotTitle: String(options.spotTitle || "") }; guardSocialPayload(invite, "meetInvite"); saveMeetInvites([...getMeetInvites(), invite]); return invite; }
  function updateInvite(inviteId, status) { const invites = getMeetInvites(); const invite = invites.find((i) => i.inviteId === String(inviteId || "")); if (!invite) return null; invite.status = status; if (status === "accepted") saveSocialLog({ acceptedInvites: [invite.inviteId] }); if (status === "declined") saveSocialLog({ declinedInvites: [invite.inviteId] }); guardSocialPayload(invite, "confirmedMeet"); saveMeetInvites(invites); return invite; }
  function cancelMeetInvite(id) { return updateInvite(id, "cancelled"); } function acceptMeetInvite(id) { return updateInvite(id, "accepted"); } function declineMeetInvite(id) { return updateInvite(id, "declined"); } function cancelConfirmedMeet(id) { return updateInvite(id, "cancelled"); }
  function completeConfirmedMeet(inviteId) { const invites = getMeetInvites(); const invite = invites.find((i) => i.inviteId === String(inviteId || "")); if (!invite) return null; invite.status = "confirmed"; invite.completedAt = new Date().toISOString(); const participants = [invite.fromUserId, invite.toUserId]; const log = updateTrustFromSharedCompletion("meet", participants, invite.inviteId); log.completedMeetups = cleanList([...(log.completedMeetups || []), invite.inviteId]); log.metUsers = cleanList([...(log.metUsers || []), ...participants.filter((id) => id !== getCurrentUserId())]); log.metAtSpots = cleanList([...(log.metAtSpots || []), invite.spotId]); writeJson(HG_SOCIAL_LOG, log); addSocialTimelineEvent("meet_completed", { inviteId: invite.inviteId, spotId: invite.spotId, spotTitle: getSpotTitle(invite), participants }); awardSocialLearningBadge("forste_mote"); guardSocialPayload(invite, "confirmedMeet"); saveMeetInvites(invites); return invite; }
  function getIncomingMeetInvites(userId = getCurrentUserId()) { return guardSocialPayload(getMeetInvites().filter((i) => i.toUserId === String(userId)), "meetInvite"); } function getOutgoingMeetInvites(userId = getCurrentUserId()) { return guardSocialPayload(getMeetInvites().filter((i) => i.fromUserId === String(userId)), "meetInvite"); } function getConfirmedMeetInvites(userId = getCurrentUserId()) { const id = String(userId); return guardSocialPayload(getMeetInvites().filter((i) => ["accepted", "confirmed"].includes(i.status) && (i.fromUserId === id || i.toUserId === id)), "confirmedMeet"); }
  function inviteCards(invites, dir) { return invites.length ? invites.map((i) => { const other = dir === "incoming" ? i.fromUserId : i.toUserId; const name = (dir === "incoming" ? i.fromDisplayName : i.toDisplayName) || getProfileByUserId(other)?.displayName || "History Go bruker"; const actions = dir === "incoming" ? `<button data-invite-action="accept" data-invite-id="${escapeHtml(i.inviteId)}" ${i.status !== "pending" ? "disabled" : ""}>Godta</button><button data-invite-action="decline" data-invite-id="${escapeHtml(i.inviteId)}" ${i.status !== "pending" ? "disabled" : ""}>Avslå</button>` : `<button data-invite-action="cancel" data-invite-id="${escapeHtml(i.inviteId)}" ${i.status !== "pending" ? "disabled" : ""}>Avbryt</button>`; return `<article class="knowledge-match-card meet-invite-card"><div><strong>${dir === "incoming" ? "Fra" : "Til"}: ${escapeHtml(name)}</strong><b>${escapeHtml(i.status)}</b></div><p><strong>Sted:</strong> ${escapeHtml(getSpotTitle(i))}</p><p><strong>Tid:</strong> ${escapeHtml(i.proposedTime || "Ikke satt")}</p><p>${escapeHtml(i.messagePreset)}</p><div class="meet-invite-actions">${actions}</div></article>`; }).join("") : `<p class="knowledge-match-empty">Ingen ${dir === "incoming" ? "innkommende" : "utgående"} møteforslag.</p>`; }
  function renderMeetInviteInbox() { const root = document.getElementById("meet-invite-inbox"); if (!root) return; const selected = root.dataset.selectedTab === "outgoing" ? "outgoing" : "incoming"; root.innerHTML = `<section class="meet-invite-inbox-panel"><div class="section-head"><h2>Møteinnboks</h2><span class="section-meta">Preset-only. Ingen chat, GPS eller visit logs.</span></div><div class="knowledge-match-controls meet-invite-tabs" role="tablist"><button data-meet-tab="incoming" aria-selected="${selected === "incoming"}">Innkommende (${getIncomingMeetInvites().length})</button><button data-meet-tab="outgoing" aria-selected="${selected === "outgoing"}">Sendte (${getOutgoingMeetInvites().length})</button></div><div class="meet-invite-list">${inviteCards(selected === "incoming" ? getIncomingMeetInvites() : getOutgoingMeetInvites(), selected)}</div></section>`; root.querySelectorAll("[data-meet-tab]").forEach((b) => b.addEventListener("click", () => { root.dataset.selectedTab = b.getAttribute("data-meet-tab") || "incoming"; renderMeetInviteInbox(); })); root.querySelectorAll("[data-invite-action]").forEach((b) => b.addEventListener("click", () => ({ accept: acceptMeetInvite, decline: declineMeetInvite, cancel: cancelMeetInvite }[b.getAttribute("data-invite-action")]?.(b.getAttribute("data-invite-id"))))); }
  function renderConfirmedMeets() { const root = document.getElementById("confirmed-meets"); if (!root) return; const rows = getConfirmedMeetInvites(); root.innerHTML = `<section class="meet-invite-inbox-panel"><div class="section-head"><h2>Bekreftede møter</h2><span class="section-meta">Avtalte møter fra kunnskapsmatcher.</span></div>${rows.length ? rows.map((i) => { const otherId = i.fromUserId === getCurrentUserId() ? i.toUserId : i.fromUserId; const other = getProfileByUserId(otherId); return `<article class="knowledge-match-card"><div><strong>${escapeHtml(getSpotTitle(i))}</strong><b>${escapeHtml(i.status)}</b></div><p><strong>Tid:</strong> ${escapeHtml(i.proposedTime || "Ikke satt")}</p><p><strong>Match:</strong> ${escapeHtml(other?.displayName || "History Go bruker")}</p><p>${escapeHtml(i.messagePreset)}</p><div class="meet-invite-actions"><button data-view-spot="${escapeHtml(i.spotId)}">Vis sted</button><button data-complete-confirmed="${escapeHtml(i.inviteId)}">Fullfør møte</button><button data-cancel-confirmed="${escapeHtml(i.inviteId)}">Avlys møte</button></div></article>`; }).join("") : `<p class="knowledge-match-empty">Ingen bekreftede møter ennå.</p>`}</section>`; root.querySelectorAll("[data-complete-confirmed]").forEach((b) => b.addEventListener("click", () => completeConfirmedMeet(b.getAttribute("data-complete-confirmed")))); root.querySelectorAll("[data-cancel-confirmed]").forEach((b) => b.addEventListener("click", () => cancelConfirmedMeet(b.getAttribute("data-cancel-confirmed")))); root.querySelectorAll("[data-view-spot]").forEach((b) => b.addEventListener("click", () => { const id = b.getAttribute("data-view-spot"); const place = (Array.isArray(window.PLACES) ? window.PLACES : []).find((p) => String(p?.id) === id); if (place && window.openPlaceCard) window.openPlaceCard(place); })); }
  function renderSocialTimeline() { const root = document.getElementById("social-history"); if (!root) return; const log = getSocialLog(); const events = guardSocialPayload((Array.isArray(readJson("hg_social_timeline_v1", [])) ? readJson("hg_social_timeline_v1", []) : []).slice(-8).reverse().map(({ createdAt, ...event }) => event), "socialTimeline"); const line = (e) => ({ meet_completed: `Met ${cleanList(e.participants).join(", ") || "andre"} at ${e.spotTitle || e.spotId || "et sted"}`, shared_route_completed: `Completed shared route with ${cleanList(e.participants).filter((id)=>id!==getCurrentUserId()).join(", ") || "andre"}`, shared_quiz_completed: `Shared quiz at ${e.placeId || e.quizId || "et sted"}`, shared_observation_completed: `Observed ${cleanList(e.tags).join(", ") || "spor"} with ${cleanList(e.participants).filter((id)=>id!==getCurrentUserId()).join(", ") || "andre"}` }[e.type] || e.type); root.innerHTML = `<section class="meet-invite-inbox-panel"><div class="section-head"><h2>Sosial historikk</h2><span class="section-meta">Privat lokalt minnelag. Ikke offentlig.</span></div><div class="social-history-grid"><span>Møtt: ${log.metUsers.length}</span><span>Fullført møter: ${log.completedMeetups.length}</span><span>Delte ruter: ${log.sharedRoutes.length}</span><span>Delte quizzer: ${log.sharedQuizzes.length}</span></div>${events.length ? `<ul class="social-timeline-list">${events.map((e)=>`<li>${escapeHtml(line(e))}</li>`).join("")}</ul>` : `<p class="knowledge-match-empty">Ingen sosial læringshistorikk ennå.</p>`}</section>`; }
  const renderSocialHistory = renderSocialTimeline;
  function renderKnowledgeMatches() { const root = document.getElementById("knowledge-match-list"); if (!root) return; const profile = getCurrentPublicProfile(); const matches = getKnowledgeMatches(profile.userId); root.innerHTML = `<div class="knowledge-match-controls"><label><input type="checkbox" id="knowledgePublicToggle" ${profile.publicProfile ? "checked" : ""}> Gjør kunnskapsprofilen offentlig</label><span>Matcher på begrep, emner, badges og domener – aldri GPS, nærhet, besøkshistorikk, følgere eller sist sett.</span></div>${profile.publicProfile ? (matches.length ? matches.map((m) => `<article class="knowledge-match-card"><div class="knowledge-match-card-head">${avatarHtml(m, "knowledge-match-avatar")}<div><strong>${escapeHtml(m.displayName)}</strong><span>${escapeHtml(m.reasonText)}</span></div><b>${m.matchScore}%</b></div><p><strong>Begrep:</strong> ${escapeHtml(m.sharedConcepts.slice(0, 4).join(", ") || "Felles domenespor")}</p><p><strong>Badges:</strong> ${escapeHtml(m.sharedBadges.slice(0, 4).join(", ") || "—")}</p><button type="button" data-view-profile="${escapeHtml(m.targetUserId)}">Vis profil</button></article>`).join("") : `<p class="knowledge-match-empty">Ingen offentlige kunnskapsmatcher ennå.</p>`) : `<p class="knowledge-match-empty">Slå på offentlig profil for å finne People Like You.</p>`}`; document.getElementById("knowledgePublicToggle")?.addEventListener("change", (e) => togglePublicProfile(Boolean(e.target.checked))); root.querySelectorAll("[data-view-profile]").forEach((b) => b.addEventListener("click", () => openMatchProfile(b.getAttribute("data-view-profile")))); }
  function openMeetInviteModal(targetUserId, spotId = "") { const profile = getProfileByUserId(targetUserId); if (!profile) return null; const place = (Array.isArray(window.PLACES) ? window.PLACES : []).find((p) => String(p?.id || "") === String(spotId || "")); const preset = PRESETS[0]; const invite = sendMeetInvite(targetUserId, spotId, { messagePreset: preset, spotTitle: place?.name || place?.title || "" }); window.showToast?.("Møteforslag sendt"); return invite; }
  function openSpotMatchList(placeId) { const matches = getKnowledgeMatches(getCurrentUserId()); const place = (Array.isArray(window.PLACES) ? window.PLACES : []).find((p) => String(p?.id || "") === String(placeId || "")); document.getElementById("spotMatchPopup")?.remove(); const popup = document.createElement("div"); popup.id = "spotMatchPopup"; popup.className = "hg-popup match-profile-popup"; popup.innerHTML = `<div class="hg-popup-inner"><div class="hg-modal match-profile-modal"><header class="hg-modal-header"><div><p class="hg-modal-meta">Møteforslag for valgt sted</p><h2 class="hg-modal-title">Møt folk${place ? ` · ${escapeHtml(place.name || place.title)}` : ""}</h2><p class="match-profile-bio">Dette viser kun kunnskapsmatcher. Det betyr ikke at noen har besøkt eller er nær stedet.</p></div></header><div class="hg-modal-body">${matches.length ? matches.map((m) => `<article class="knowledge-match-card"><div><strong>${escapeHtml(m.displayName)}</strong><b>${m.matchScore}%</b></div><p>${escapeHtml(m.reasonText)}</p><button data-spot-invite="${escapeHtml(m.targetUserId)}">Foreslå dette stedet</button></article>`).join("") : `<p class="knowledge-match-empty">Ingen matcher tilgjengelig.</p>`}<div class="match-profile-actions"><button data-spot-close>Lukk</button></div></div></div></div>`; popup.addEventListener("click", (e) => { if (e.target === popup || e.target?.closest?.("[data-spot-close]")) popup.remove(); const id = e.target?.closest?.("[data-spot-invite]")?.getAttribute("data-spot-invite"); if (id) { sendMeetInvite(id, placeId, { messagePreset: PRESETS[0], spotTitle: place?.name || place?.title || "" }); popup.remove(); window.showToast?.("Møteforslag sendt"); } }); document.body.appendChild(popup); return popup; }

  const CIRCLES_KEY = "hg_learning_circles_v1";
  const ROUTES_KEY = "hg_shared_routes_v1";
  const OPEN_MEETUPS_KEY = "hg_open_meetups_v1";
  const SHARED_QUIZZES_KEY = "hg_shared_quizzes_v1";
  const SHARED_OBSERVATIONS_KEY = "hg_shared_observations_v1";
  const ROUTE_STATES = new Set(["planned", "active", "completed"]);
  const QUIZ_MODES = new Set(["cooperative", "compare", "discussion"]);

  const DEFAULT_CIRCLES = Object.freeze([
    { circleId: "circle-oslo-industrial", title: "Oslo Industrial History", members: ["mock-saga"], focusDomains: ["historie", "by", "industri"], activeSpots: ["oslo_gassverk", "vinmonopolets_hovedlager"] },
    { circleId: "circle-hidden-architecture", title: "Hidden Architecture", members: ["mock-saga", "mock-ida"], focusDomains: ["arkitektur", "by", "kunst"], activeSpots: ["telthusbakken", "universitetets_gamle_kjemi"] },
    { circleId: "circle-political-oslo", title: "Political Oslo", members: ["mock-ida"], focusDomains: ["politikk", "historie", "offentlighet"], activeSpots: ["eidsvoll", "stortinget"] },
    { circleId: "circle-forest-biology", title: "Forest Biology", members: ["mock-ask"], focusDomains: ["natur", "biologi", "vitenskap"], activeSpots: ["sofienbergparken"] }
  ]);

  function pairKey(a, b) { return cleanList([a, b]).sort().join("::"); }
  function getSocialRelations(log = getSocialLog()) { return Array.isArray(log.relations) ? log.relations : []; }
  function upsertRelation(log, otherUserId, patch = {}) { const other = String(otherUserId || ""); if (!other) return log; const relations = getSocialRelations(log); const found = relations.find((r) => r.userId === other) || { userId: other, metAtSpots: [], sharedQuizzes: [], sharedRoutes: [], sharedObservations: [], repeatedMeetCount: 0 }; const previous = { metAtSpots: cleanList(found.metAtSpots), sharedQuizzes: cleanList(found.sharedQuizzes), sharedRoutes: cleanList(found.sharedRoutes), sharedObservations: cleanList(found.sharedObservations), repeatedMeetCount: Number(found.repeatedMeetCount || 0) }; Object.assign(found, patch); found.metAtSpots = cleanList([...previous.metAtSpots, ...cleanList(patch.metAtSpots)]); found.sharedQuizzes = cleanList([...previous.sharedQuizzes, ...cleanList(patch.sharedQuizzes)]); found.sharedRoutes = cleanList([...previous.sharedRoutes, ...cleanList(patch.sharedRoutes)]); found.sharedObservations = cleanList([...previous.sharedObservations, ...cleanList(patch.sharedObservations)]); found.repeatedMeetCount = Math.max(previous.repeatedMeetCount, Number(patch.repeatedMeetCount || 0)); if (!relations.includes(found)) relations.push(found); log.relations = relations; return log; }
  function getAcceptedBetween(a, b) { const key = pairKey(a, b); return getMeetInvites().filter((i) => ["accepted", "confirmed"].includes(i.status) && pairKey(i.fromUserId, i.toUserId) === key); }
  function calculateTrustScore(userIdA, userIdB) { const a = String(userIdA || getCurrentUserId()), b = String(userIdB || ""); const rel = getSocialRelations().find((r) => r.userId === b) || {}; const accepted = getAcceptedBetween(a, b).length; const completed = cleanList(getSocialLog().completedMeetups).filter((id) => getMeetInvites().some((i) => i.inviteId === id && pairKey(i.fromUserId, i.toUserId) === pairKey(a, b))).length; const repeated = Number(rel.repeatedMeetCount || 0); const routes = cleanList(rel.sharedRoutes).length; const quizzes = cleanList(rel.sharedQuizzes).length; const observations = cleanList(rel.sharedObservations).length; const raw = Math.min(1, completed * 0.28 + repeated * 0.10 + routes * 0.24 + quizzes * 0.20 + observations * 0.18); const trustScore = Math.round(raw * 100) / 100; const trustTier = trustScore >= 0.75 ? "close" : trustScore >= 0.5 ? "trusted" : trustScore >= 0.25 ? "known" : "new"; return { trustScore, trustTier }; }
  function normalizeCircle(c) { return { circleId: String(c?.circleId || `circle-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`), title: String(c?.title || "Ny læringssirkel"), members: cleanList(c?.members), focusDomains: cleanList(c?.focusDomains), activeSpots: cleanList(c?.activeSpots), invites: Array.isArray(c?.invites) ? c.invites : [] }; }
  function getLearningCircles() { const stored = Array.isArray(readJson(CIRCLES_KEY, [])) ? readJson(CIRCLES_KEY, []) : []; const byId = new Map([...DEFAULT_CIRCLES, ...stored].map(normalizeCircle).map((c) => [c.circleId, c])); return Array.from(byId.values()); }
  function saveLearningCircles(circles) { writeJson(CIRCLES_KEY, (circles || []).map(normalizeCircle)); renderLearningCircles(); }
  function createLearningCircle(data = {}) { const circle = normalizeCircle({ ...data, members: cleanList([getCurrentUserId(), ...(data.members || [])]) }); saveLearningCircles([...getLearningCircles(), circle]); return circle; }
  function joinLearningCircle(circleId, userId = getCurrentUserId()) { if (window.canJoinCircle && !window.canJoinCircle(userId, circleId)) return null; const circles = getLearningCircles(); const c = circles.find((x) => x.circleId === String(circleId)); if (c) c.members = cleanList([...(c.members || []), userId]); saveLearningCircles(circles); return c || null; }
  function inviteToCircle(circleId, targetId, fromUserId = getCurrentUserId()) { if (window.isBlocked?.(fromUserId, targetId) || window.getPrivacySettings?.(targetId)?.allowCircleInvites === false) return null; const circles = getLearningCircles(); const c = circles.find((x) => x.circleId === String(circleId)); if (!c || !cleanList(c.members).includes(String(fromUserId))) return null; const invite = { inviteId: `circle-invite-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, fromUserId: String(fromUserId), toUserId: String(targetId), status: "pending", createdAt: new Date().toISOString() }; c.invites = [...(Array.isArray(c.invites) ? c.invites : []), invite]; saveLearningCircles(circles); return invite; }
  function acceptCircleInvite(inviteId, userId = getCurrentUserId()) { const circles = getLearningCircles(); let found = null; circles.forEach((c) => (c.invites || []).forEach((i) => { if (i.inviteId === String(inviteId) && i.toUserId === String(userId)) { i.status = "accepted"; c.members = cleanList([...(c.members || []), userId]); found = c; } })); saveLearningCircles(circles); return found; }
  function declineCircleInvite(inviteId, userId = getCurrentUserId()) { const circles = getLearningCircles(); let found = null; circles.forEach((c) => (c.invites || []).forEach((i) => { if (i.inviteId === String(inviteId) && i.toUserId === String(userId)) { i.status = "declined"; found = c; } })); saveLearningCircles(circles); return found; }
  function leaveCircle(circleId, userId = getCurrentUserId()) { const circles = getLearningCircles(); const c = circles.find((x) => x.circleId === String(circleId)); if (c) c.members = cleanList(c.members).filter((id) => id !== String(userId)); saveLearningCircles(circles); return c || null; }
  function removeFromCircle(circleId, targetId, actorId = getCurrentUserId()) { const circles = getLearningCircles(); const c = circles.find((x) => x.circleId === String(circleId)); if (c && cleanList(c.members).includes(String(actorId))) c.members = cleanList(c.members).filter((id) => id !== String(targetId)); saveLearningCircles(circles); return c || null; }
  function getRecommendedCircles(userId = getCurrentUserId()) { const profile = getAllProfiles().find((p) => p.userId === String(userId)) || getCurrentPublicProfile(); const fp = buildKnowledgeFingerprint(profile); const domains = new Set([...Object.keys(fp.domainVector), ...profile.interests, ...profile.badges, ...profile.completedEmner]); const trustedIds = getKnowledgeMatches(userId).filter((m) => calculateTrustScore(userId, m.targetUserId).trustScore >= 0.25).map((m) => m.targetUserId); return getLearningCircles().filter((c) => !c.members.includes(String(userId))).map((c) => ({ ...c, recommendationScore: cleanList(c.focusDomains).filter((d) => domains.has(d)).length * 2 + c.members.filter((id) => trustedIds.includes(id)).length })).filter((c) => c.recommendationScore > 0).sort((a, b) => b.recommendationScore - a.recommendationScore); }
  function getSharedRoutes() { return (Array.isArray(readJson(ROUTES_KEY, [])) ? readJson(ROUTES_KEY, []) : []).map((r) => ({ routeId: String(r?.routeId || ""), participants: cleanList(r?.participants), spots: cleanList(r?.spots), routeType: ["solo", "pair", "circle"].includes(r?.routeType) ? r.routeType : "solo", circleId: String(r?.circleId || ""), completionState: ROUTE_STATES.has(r?.completionState) ? r.completionState : "planned" })).filter((r) => r.routeId); }
  function saveSharedRoutes(routes) { writeJson(ROUTES_KEY, routes || []); renderSocialProgression(); }
  function startSharedRoute(data = {}) { const route = { routeId: `route-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, participants: cleanList(data.participants || [getCurrentUserId()]), spots: cleanList(data.spots), routeType: data.routeType || "solo", circleId: String(data.circleId || ""), completionState: "active", startedAt: new Date().toISOString() }; saveSharedRoutes([...getSharedRoutes(), route]); addSocialTimelineEvent("shared_route_started", { routeId: route.routeId, participants: route.participants, spots: route.spots }); return route; }
  const createSharedRoute = startSharedRoute;
  function joinSharedRoute(routeId, userId = getCurrentUserId()) { const routes = getSharedRoutes(); const r = routes.find((x) => x.routeId === String(routeId)); if (r) r.participants = cleanList([...r.participants, userId]); saveSharedRoutes(routes); return r || null; }
  function completeSharedRoute(routeId) { const routes = getSharedRoutes(); const r = routes.find((x) => x.routeId === String(routeId)); if (r) { r.completionState = "completed"; r.completedAt = new Date().toISOString(); const log = updateTrustFromSharedCompletion("route", r.participants, r.routeId); log.sharedRoutes = cleanList([...(log.sharedRoutes || []), r.routeId]); writeJson(HG_SOCIAL_LOG, log); addSocialTimelineEvent("shared_route_completed", { routeId: r.routeId, participants: r.participants, spots: r.spots }); awardSocialLearningBadge("forste_felles_rute"); } saveSharedRoutes(routes); renderCircleActivity(); return r || null; }
  function getSocialReputation(userId = getCurrentUserId()) { const uid = String(userId); const routes = getSharedRoutes().filter((r) => r.participants.includes(uid) && r.completionState === "completed").length; const quizzes = getSharedQuizzes().filter((q) => q.participants.includes(uid) && q.completionState === "completed").length; const observations = (Array.isArray(readJson(SHARED_OBSERVATIONS_KEY, [])) ? readJson(SHARED_OBSERVATIONS_KEY, []) : []).filter((o) => cleanList(o.users || o.participants).includes(uid)).length; const hosted = getOpenMeetups().filter((m) => m.hostUserId === uid && cleanList(m.participants).length > 1).length; const circles = getLearningCircles().filter((c) => c.members.includes(uid)).length; const relations = getSocialRelations().filter((r) => Number(r.repeatedMeetCount || 0) > 0 || cleanList(r.sharedRoutes).length || cleanList(r.sharedQuizzes).length || cleanList(r.sharedObservations).length).length; const points = hosted * 3 + quizzes * 2 + routes * 3 + observations * 2 + circles * 2 + relations * 2; if (points >= 14) return "Historisk følgesvenn"; if (hosted >= 2 || routes >= 2) return "Guide"; if (quizzes >= 2) return "Læringspartner"; if (circles >= 2) return "Sirkelbygger"; return "Utforsker"; }
  function getOpenMeetups() { return Array.isArray(readJson(OPEN_MEETUPS_KEY, [])) ? readJson(OPEN_MEETUPS_KEY, []) : []; }
  function createOpenMeetup(data = {}) { const meetup = { meetupId: `meetup-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, hostUserId: getCurrentUserId(), title: String(data.title || "History Go-møte"), spotId: String(data.spotId || ""), theme: String(data.theme || "Felles utforskning"), scheduledAt: String(data.scheduledAt || ""), participants: cleanList([getCurrentUserId(), ...(data.participants || [])]) }; writeJson(OPEN_MEETUPS_KEY, [...getOpenMeetups(), meetup]); renderSocialProgression(); return meetup; }
  function joinOpenMeetup(meetupId, userId = getCurrentUserId()) { const rows = getOpenMeetups(); const m = rows.find((x) => x.meetupId === String(meetupId)); if (m) m.participants = cleanList([...m.participants, userId]); writeJson(OPEN_MEETUPS_KEY, rows); renderSocialProgression(); return m || null; }
  function getSharedQuizzes() { return Array.isArray(readJson(SHARED_QUIZZES_KEY, [])) ? readJson(SHARED_QUIZZES_KEY, []) : []; }
  function startSharedQuiz(placeIdOrData = {}, participantIds = [], mode = "co-op") { const data = typeof placeIdOrData === "object" ? placeIdOrData : { placeId: placeIdOrData, participants: participantIds, mode }; const normalizedMode = data.mode === "co-op" ? "cooperative" : data.mode; const q = { sharedQuizId: `shared-quiz-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, placeId: String(data.placeId || data.spotId || ""), quizId: String(data.quizId || data.placeId || ""), mode: QUIZ_MODES.has(normalizedMode) ? normalizedMode : "cooperative", participants: cleanList([getCurrentUserId(), ...(data.participants || [])]), answers: data.answers || {}, completionState: "active", startedAt: new Date().toISOString() }; writeJson(SHARED_QUIZZES_KEY, [...getSharedQuizzes(), q]); return q; }
  function completeSharedQuiz(sharedQuizId, answers = {}) { const rows = getSharedQuizzes(); const q = rows.find((x) => x.sharedQuizId === String(sharedQuizId)); if (q) { q.answers = { ...(q.answers || {}), [getCurrentUserId()]: answers }; q.completionState = "completed"; q.completedAt = new Date().toISOString(); const log = updateTrustFromSharedCompletion("quiz", q.participants, q.sharedQuizId); log.sharedQuizzes = cleanList([...(log.sharedQuizzes || []), q.sharedQuizId]); writeJson(HG_SOCIAL_LOG, log); addSocialTimelineEvent("shared_quiz_completed", { sharedQuizId: q.sharedQuizId, placeId: q.placeId, participants: q.participants }); awardSocialLearningBadge("forste_felles_quiz"); } writeJson(SHARED_QUIZZES_KEY, rows); renderCircleActivity(); return q || null; }
  function compareSharedQuizAnswers(sharedQuizId) { const q = getSharedQuizzes().find((x) => x.sharedQuizId === String(sharedQuizId)); const answers = q?.answers || {}; return { sharedQuizId: String(sharedQuizId || ""), participants: Object.keys(answers), sharedAnswers: Object.entries(answers) }; }
  function attachCollaborators(observation, participantIds = []) { observation.users = cleanList([...(observation.users || []), ...participantIds]); return observation; }
  function linkObservationToMeet(observation, meetId = "") { observation.meetId = String(meetId || observation.meetId || ""); return observation; }
  function updateTrustFromObservation(observation) { const log = updateTrustFromSharedCompletion("observation", observation.users || [], observation.observationId); log.sharedObservations = cleanList([...(log.sharedObservations || []), observation.observationId]); writeJson(HG_SOCIAL_LOG, log); return log; }
  function createSharedObservation(data = {}) { let observation = { observationId: `obs-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, spotId: String(data.spotId || data.targetId || ""), users: cleanList(data.users || data.participants || [getCurrentUserId()]), observations: cleanList(data.observations || data.selected), tags: cleanList(data.tags), createdAt: new Date().toISOString() }; observation = attachCollaborators(observation, data.collaborators || data.participantIds || []); observation = linkObservationToMeet(observation, data.meetId || ""); writeJson(SHARED_OBSERVATIONS_KEY, [...(Array.isArray(readJson(SHARED_OBSERVATIONS_KEY, [])) ? readJson(SHARED_OBSERVATIONS_KEY, []) : []), observation]); updateTrustFromObservation(observation); addSocialTimelineEvent("shared_observation_completed", { observationId: observation.observationId, spotId: observation.spotId, participants: observation.users }); awardSocialLearningBadge("observator"); renderCircleActivity(); return observation; }
  function renderSocialProgression() { const root = document.getElementById("social-progression"); if (!root) return; const rep = getSocialReputation(); const routes = getSharedRoutes().filter((r) => r.participants.includes(getCurrentUserId())); const meetups = getOpenMeetups(); root.innerHTML = `<section class="meet-invite-inbox-panel social-progression-panel"><div class="section-head"><h2>Sosial progresjon</h2><span class="section-meta">Tillit, ruter og omdømme uten følgere, likes eller feed.</span></div><div class="social-history-grid"><span>Identitet: ${escapeHtml(rep)}</span><span>Delte ruter: ${routes.length}</span><span>Åpne møter: ${meetups.length}</span></div><div class="meet-invite-actions"><button data-create-route>Lag delt rute</button><button data-create-meetup>Arranger møte</button></div></section>`; root.querySelector("[data-create-route]")?.addEventListener("click", () => createSharedRoute({ routeType: "pair" })); root.querySelector("[data-create-meetup]")?.addEventListener("click", () => createOpenMeetup({ title: "Industrial Oslo Walk", theme: "Industrial history" })); }
  function renderLearningCircles() { const root = document.getElementById("learning-circles"); if (!root) return; const userId = getCurrentUserId(); const joined = getLearningCircles().filter((c) => c.members.includes(userId)); const recs = getRecommendedCircles(userId).slice(0, 4); const card = (c, action) => `<article class="knowledge-match-card"><div><strong>${escapeHtml(c.title)}</strong><b>${cleanList(c.focusDomains).length} felt</b></div><p>${escapeHtml(cleanList(c.focusDomains).join(" · ") || "Åpen utforskning")}</p>${action ? `<button data-join-circle="${escapeHtml(c.circleId)}">Bli med</button>` : ""}</article>`; root.innerHTML = `<section class="meet-invite-inbox-panel learning-circles-panel"><div class="section-head"><h2>Læringssirkler</h2><span class="section-meta">Små tilbakevendende grupper: guild / study circle / exploration society.</span></div><h3>Dine sirkler</h3>${joined.length ? joined.map((c) => card(c, false)).join("") : `<p class="knowledge-match-empty">Ingen circles ennå.</p>`}<h3>Anbefalt</h3>${recs.length ? recs.map((c) => card(c, true)).join("") : `<p class="knowledge-match-empty">Ingen anbefalte circles ennå.</p>`}<div class="meet-invite-actions"><button data-create-circle>Opprett ny circle</button></div></section>`; root.querySelectorAll("[data-join-circle]").forEach((b) => b.addEventListener("click", () => joinLearningCircle(b.getAttribute("data-join-circle")))); root.querySelector("[data-create-circle]")?.addEventListener("click", () => createLearningCircle({ title: "Ny utforskersirkel", focusDomains: cleanList(getCurrentPublicProfile().interests).slice(0, 3) })); }

  function renderCircleActivity() { const root = document.getElementById("circle-activity"); if (!root) return; const uid = getCurrentUserId(); const circles = getLearningCircles().filter((c) => c.members.includes(uid)); const routes = getSharedRoutes().filter((r) => r.participants.includes(uid)).slice(-4); const quizzes = getSharedQuizzes().filter((q) => q.participants.includes(uid)).slice(-4); const observations = (Array.isArray(readJson(SHARED_OBSERVATIONS_KEY, [])) ? readJson(SHARED_OBSERVATIONS_KEY, []) : []).filter((o) => cleanList(o.users).includes(uid)).slice(-4).map(({ createdAt, ...observation }) => observation); const meetups = getOpenMeetups().filter((m) => cleanList(m.participants).includes(uid)).slice(-4); guardSocialPayload({ circles, routes, quizzes, observations, meetups }, "circleActivity"); root.innerHTML = `<section class="meet-invite-inbox-panel"><div class="section-head"><h2>Sirkelaktivitet</h2><span class="section-meta">Kun synlig for medlemmer.</span></div>${circles.length ? `<div class="social-history-grid"><span>Nye ruter: ${routes.length}</span><span>Nye observasjoner: ${observations.length}</span><span>Nye quizzer: ${quizzes.length}</span><span>Nye meetups: ${meetups.length}</span></div>` : `<p class="knowledge-match-empty">Bli med i en circle for intern aktivitet.</p>`}</section>`; }

  window.HG_PUBLIC_PROFILES = HG_PUBLIC_PROFILES; window.HG_SOCIAL_LOG = HG_SOCIAL_LOG; window.HG_PUBLIC_PROFILE = getCurrentPublicProfile();
  Object.assign(window, { getCurrentPublicProfile, savePublicProfile, togglePublicProfile, buildKnowledgeFingerprint, getKnowledgeMatches, calculateMatchScore, renderKnowledgeMatches, openMatchProfile, renderMatchProfile, sendMeetInvite, cancelMeetInvite, acceptMeetInvite, declineMeetInvite, renderMeetInviteInbox, getIncomingMeetInvites, getOutgoingMeetInvites, renderConfirmedMeets, getConfirmedMeetInvites, cancelConfirmedMeet, completeConfirmedMeet, openSpotMatchList, calculateTrustScore, getLearningCircles, createLearningCircle, joinLearningCircle, getRecommendedCircles, getSharedRoutes, createSharedRoute, joinSharedRoute, completeSharedRoute, getSocialReputation, getOpenMeetups, createOpenMeetup, joinOpenMeetup, startSharedQuiz, completeSharedQuiz, compareSharedQuizAnswers, compareAnswers: compareSharedQuizAnswers, createSharedObservation, attachCollaborators, linkObservationToMeet, updateTrustFromObservation, renderSocialTimeline, renderSocialProgression, renderLearningCircles, renderCircleActivity, updateKnowledgeFingerprint, updateSocialMatchIndex, checkSharedQuizOpportunities, startSharedRoute, inviteToCircle, acceptCircleInvite, declineCircleInvite, leaveCircle, removeFromCircle });
  window.HGKnowledgeMatch = { HG_PUBLIC_PROFILES, HG_SOCIAL_LOG, presets: PRESETS, getCurrentPublicProfile, savePublicProfile, togglePublicProfile, buildKnowledgeFingerprint, getKnowledgeMatches, calculateMatchScore, renderKnowledgeMatches, openMatchProfile, renderMatchProfile, sendMeetInvite, cancelMeetInvite, acceptMeetInvite, declineMeetInvite, renderMeetInviteInbox, getIncomingMeetInvites, getOutgoingMeetInvites, renderConfirmedMeets, getConfirmedMeetInvites, cancelConfirmedMeet, completeConfirmedMeet, openSpotMatchList, calculateTrustScore, getLearningCircles, createLearningCircle, joinLearningCircle, getRecommendedCircles, getSharedRoutes, createSharedRoute, joinSharedRoute, completeSharedRoute, getSocialReputation, getOpenMeetups, createOpenMeetup, joinOpenMeetup, startSharedQuiz, completeSharedQuiz, compareSharedQuizAnswers, compareAnswers: compareSharedQuizAnswers, createSharedObservation, attachCollaborators, linkObservationToMeet, updateTrustFromObservation, renderSocialTimeline, renderSocialProgression, renderLearningCircles, renderCircleActivity, updateKnowledgeFingerprint, updateSocialMatchIndex, checkSharedQuizOpportunities, startSharedRoute, inviteToCircle, acceptCircleInvite, declineCircleInvite, leaveCircle, removeFromCircle };
  document.addEventListener("DOMContentLoaded", () => { renderKnowledgeMatches(); renderMeetInviteInbox(); renderConfirmedMeets(); renderSocialTimeline(); renderSocialProgression(); renderLearningCircles(); renderCircleActivity(); window.refreshSocialIndex?.(); });
})();
