(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis;
  const VERSION=1;
  const FORBIDDEN_FIELDS=['lat','lng','latitude','longitude','gps','location','liveLocation','presence','isOnline','lastSeen','visitLog','visitedAt','timestampedVisits','followers','followerCount','following','feedTracking'];
  const FORBIDDEN_WORDS=['nearby','distance','GPS','live location','online','last seen','followers','following','feed','avstand','i nærheten','live-posisjon','pålogget','sist sett','følgere','følger'];
  let lastSnapshot=null;
  const arr=v=>Array.isArray(v)?v.filter(x=>x!=null):[];
  const str=v=>String(v==null?'':v);
  const num=v=>Number.isFinite(Number(v))?Number(v):0;
  const uniq=v=>Array.from(new Set(arr(v).map(x=>typeof x==='object'?str(x.id||x.key||x.title||x.label||x.name||JSON.stringify(x)):str(x)).filter(Boolean)));
  function now(){return new Date().toISOString();}
  function testMode(){try{return root.localStorage?.getItem?.('HG_TEST_MODE')==='1'||root.HG_TEST_MODE===true||root.HG_TEST_MODE==='1'||root.TEST_MODE===true;}catch{return root.HG_TEST_MODE===true||root.HG_TEST_MODE==='1'||root.TEST_MODE===true;}}
  function call(fn,fallback){try{return typeof fn==='function'?fn():fallback;}catch(e){return fallback;}}
  async function callAsync(fn,fallback){try{return typeof fn==='function'?await fn():fallback;}catch(e){return fallback;}}
  function issueList(v){return arr(v).map(x=>typeof x==='string'?{message:x}:x).filter(Boolean);}
  function warning(msg,key,source){return {key:key||'warning',message:msg,source:source||'today_hub'};}
  function blocker(msg,key,source){return {key:key||'blocker',message:msg,source:source||'today_hub'};}
  function routeFor(extra){const t=extra?.target; if(extra?.routeKey)return extra.routeKey; if(t==='HG_PublicProfilePreviewPanel')return 'open_public_profile_preview'; if(t==='HGSocialMatchGraphPanel'||t==='HG_SocialMatchGraphPanel')return 'open_match_graph'; if(t==='HG_RuntimeHealthPanel')return 'open_runtime_health'; if(t==='HG_SocialDemoPanel')return 'open_social_demo'; return 'read_only';}
  function action(id,type,title,reason,priority,source,extra){const e=extra||{}; const routeKey=routeFor(e); return Object.assign({id,type,title,subtitle:'',reason,priority:num(priority),source,target:null,enabled:true,actionKind:routeKey==='read_only'?'read_only':'open_panel',routeKey,payload:{},safetyLabel:routeKey==='read_only'?'Lesemodus':routeKey==='open_social_demo'?'Testmodus':'Trygg visning'},e,{routeKey});}
  function collectCivication(){
    const warnings=[], blockers=[];
    const debug=call(()=>root.HG_CiviDebug?.snapshot?.(),null);
    const health=call(()=>root.HG_CiviDebug?.health?.(),null);
    const profile=call(()=>root.HG_CiviProfileSnapshot?.(),null);
    const workday=call(()=>root.HG_CiviWorkdaySnapshot?.(),null);
    const economy=call(()=>root.HG_CiviEconomySnapshot?.(),null);
    const home=call(()=>root.CivicationHome?.getHomeSnapshot?.(),null);
    [health,debug,profile,workday,economy,home].forEach((x,i)=>{issueList(x?.warnings).forEach(w=>warnings.push(w)); issueList(x?.blockers).forEach(b=>blockers.push(b));});
    if(!debug&&!profile&&!workday&&!economy&&!home) warnings.push(warning('Civication-readmodeller mangler på denne siden.','civication_missing','civication'));
    const role=profile?.role||debug?.profile?.role||debug?.role||null;
    const salary=profile?.salary??workday?.salary??debug?.salary??null;
    const wallet=economy?.wallet??economy?.balance??debug?.wallet??profile?.wallet??null;
    const activeJob=workday?.activeJob||workday?.job||debug?.activeJob||profile?.activeJob||null;
    return {available:!!(debug||profile||workday||economy||home),role,salary,wallet,activeJob,workdayStatus:workday?.status||workday?.phase||debug?.workdayStatus||null,economyStatus:economy?.status||economy?.summary||null,homeStatus:home?.housingStatus||home?.status||home?.currentDistrictId||null,warnings,blockers,_raw:{debug,health,profile,workday,economy,home}};
  }
  function collectSocial(){
    const warnings=[],blockers=[]; const summary=call(()=>root.HG_SocialSignals?.getSummary?.(),null); const profile=call(()=>root.HG_PublicProfileReadModel?.getReadModel?.(),null); const graph=call(()=>root.HG_SocialMatchGraph?.buildMatchGraph?.({limit:10}),null); const health=call(()=>root.HG_SocialDebug?.health?.(),null);
    [summary,profile,graph,health].forEach(x=>{issueList(x?.warnings).forEach(w=>warnings.push(w)); issueList(x?.blockers).forEach(b=>blockers.push(b));}); if(!summary&&!profile&&!graph) warnings.push(warning('Sosiale readmodeller mangler på denne siden.','social_missing','social'));
    const matches=arr(graph?.matches).slice(0,5).map(m=>({id:m.id,candidateId:m.candidateId,score:m.score,level:m.level,reasons:arr(m.reasons).slice(0,2),suggestedActivities:arr(m.suggestedActivities)}));
    return {available:!!(summary||profile||graph),publicProfileEnabled:profile?.publicProfileEnabled===true,signalCount:num(summary?.total||summary?.signalCount||profile?.counts?.signalCount),matchCount:num(graph?.matches?.length),topMatches:matches,topReasons:uniq(matches.flatMap(m=>m.reasons)).slice(0,5),suggestedActivities:uniq(matches.flatMap(m=>m.suggestedActivities)).slice(0,8),warnings,blockers,privacyLabels:['lokalt','kunnskapsbasert','uten posisjonssporing'],_raw:{summary,profile,graph,health}};
  }
  function collectLearning(social){
    const warnings=[]; const hist=call(()=>root.HGLearningLog?.getQuizHistory?.(),null)||call(()=>root.HGLearningLog?.quizHistory?.(),null); if(!hist) warnings.push(warning('Quizhistorikk er ikke tilgjengelig.','quiz_history_missing','learning'));
    const summary=social?._raw?.summary||{}; const domains=uniq(summary.knowledgeDomains||summary.domains||summary.topDomains||social?._raw?.profile?.sections?.knowledgeDomains?.items||Object.keys(/** @type {any} */ (root).TAGS_REGISTRY||{})).slice(0,6);
    const suggested=domains.length?domains.slice(0,3):['historie'];
    return {completedQuizCount:arr(hist).length,topDomains:domains,weakDomains:[],suggestedDomains:suggested,suggestedQuizActions:suggested.map(d=>`Ta en quiz i ${d}`),suggestedPlaceActions:suggested.map(d=>`Besøk et sted som styrker ${d}`),warnings};
  }
  function collectRoutes(social){const warnings=[]; const g=social?._raw?.graph; const routeGlobals=call(()=>root.HGRoutes?.getRoutes?.(),null)||call(()=>root.HistoricalRoutes?.getRoutes?.(),null)||/** @type {any} */ (root).ROUTES||root.HISTORICAL_ROUTES; const suggested=arr(routeGlobals).slice(0,5).map(r=>({id:r.id||r.routeId||r.title,title:r.title||r.name||r.theme||r.id})); const shared=arr(g?.matches).filter(m=>arr(m.suggestedActivities).includes('shared_route')).slice(0,5).map(m=>({matchId:m.id,title:'Felles rute med kunnskapsmatch'})); if(!routeGlobals&&!shared.length) warnings.push(warning('Rute-readmodell er ikke tilgjengelig her.','routes_missing','routes')); return {available:!!(routeGlobals||shared.length),suggestedRoutes:suggested,sharedRouteOpportunities:shared,warnings};}
  function collectObservations(social){const warnings=[]; const tags=uniq(social?._raw?.summary?.observationTags||social?._raw?.profile?.sections?.observationTags?.items||[]).slice(0,8); if(!tags.length) warnings.push(warning('Ingen observasjonstagger funnet ennå.','observation_tags_missing','observations')); const places=arr(root.PLACES); const byPlaces=places.filter(p=>str(p?.categoryId||p?.category||p?.subject_id)==='by'); const suggestedPlaces=(byPlaces.length?byPlaces:places).slice(0,5); return {available:tags.length>0,observationTagCount:tags.length,suggestedObservationTags:tags,suggestedObservationPlaces:suggestedPlaces.map(p=>({placeId:p.id,title:p.title||p.name||p.id})),warnings};}
  function buildActions(ctx){const a=[]; const c=ctx.civication, raw=c._raw||{}; const quizTarget=arr(root.PLACES).find(p=>['aker_brygge','barcode','bjorvika','oslo_s','karl_johan','torggata','slottsparken'].includes(str(p?.id)))?.id||'aker_brygge'; const observationPlace=ctx.observations.suggestedObservationPlaces[0]||null; const suggestedRoute=ctx.routes.suggestedRoutes[0]||null; if(c.blockers.length)a.push(action('fix-blockers','diagnostics','Se blokkere','Blokkere bør løses før videre testing.',100,'diagnostics',{actionKind:'open_panel',target:'HG_RuntimeHealthPanel'})); if(raw.workday){const active=!!(c.activeJob||/active|started|in_progress|pågår/i.test(str(c.workdayStatus))); a.push(action(active?'continue-workday':'start-workday','workday',active?'Fortsett arbeidsdagen':'Sjekk jobbstatus','Arbeidsdagen er relevant for dagens neste steg.',active?90:62,'workday',{subtitle:str(c.activeJob?.title||c.activeJob||c.workdayStatus||''),target:'Civication jobbflate',routeKey:'open_workday',safetyLabel:'Åpner Civication'}));}
    const econ=raw.economy||{}; const wallet=num(c.wallet); const net=num(econ.net||econ.netIncome||econ.dailyNet||econ.weeklyNet); if(net<0||wallet>0&&wallet<50)a.push(action('review-economy','economy',wallet<50?'Ta læringsrunde før nye kjøp':'Se økonomi før nye kjøp','Økonomien viser press eller lav saldo.',84,'economy',{target:'Civication økonomi',routeKey:'open_civication_summary'}));
    const home=raw.home||{}; if(home.rentPressure||home.rentDue||/pressure|due|risk|warning|press/i.test(str(c.homeStatus)))a.push(action('review-home','home','Sjekk bolig','Bolig eller husleie bør sjekkes før nye valg.',82,'home',{target:'Civication bolig',routeKey:'open_home'}));
    arr(home.blockedMoves||home.lockedDistricts).slice(0,1).forEach(()=>a.push(action('work-new-neighborhood','home','Jobb mot nytt nabolag','Et nabolag er låst, men kan planlegges fra trygge progresjonssignaler.',58,'home',{target:'Civication bolig',routeKey:'open_home'})));
    ctx.learning.suggestedDomains.slice(0,2).forEach((d,i)=>a.push(action(`quiz-${i}`,'learning',`Ta en quiz i ${d}`,'Læring kan styrke profilen og gi flere trygge forslag.',60-i,'learning',{target:'Quiz',routeKey:'open_quiz',payload:{targetId:quizTarget},safetyLabel:'Åpner quiz'})));
    if(ctx.social.matchCount>0)a.push(action('view-matches','social','Se kunnskapsmatchene dine','Det finnes kunnskapsbaserte matcher å lese.',55,'social',{actionKind:'open_panel',target:'HGSocialMatchGraphPanel'}));
    a.push(action('view-public-profile','profile',ctx.social.publicProfileEnabled?'Se offentlig profil':'Bygg offentlig profil fra læringsspor','Profil-previewen bygger på lokale læringsspor.',35,'social',{actionKind:root.HG_PublicProfilePreviewPanel?.render?'open_panel':'read_only',target:'HG_PublicProfilePreviewPanel'}));
    if(suggestedRoute)a.push(action('view-route','routes','Se foreslått rute','Det finnes en rute du kan åpne og utforske.',45,'routes',{target:'Ruter',routeKey:'open_route_viewer',payload:{targetId:suggestedRoute.id},safetyLabel:'Åpner ruten'})); if(ctx.routes.sharedRouteOpportunities.length&&testMode())a.push(action('shared-route','routes','Felles rute med kunnskapsmatch','Match graph viser felles ruteaktivitet i testmodus.',48,'routes',{target:'HGSocialMatchGraphPanel',actionKind:'open_panel'}));
    if(observationPlace)a.push(action('add-observation','observations','Legg til observasjon','Observasjoner kan styrke læringsspor når du velger det selv.',30,'observations',{target:'Observasjoner',routeKey:'open_observation_ui',payload:{placeId:observationPlace.placeId,targetId:observationPlace.placeId,subjectId:'by'},safetyLabel:'Åpner observasjon'}));
    return a.sort((x,y)=>y.priority-x.priority);
  }
  function scanPrivacy(value){const found=[]; const seen=new WeakSet(); function walk(v,path,key){if(v&&typeof v==='object'){if(seen.has(v))return; seen.add(v); Object.keys(v).forEach(k=>{const p=path?`${path}.${k}`:k; if(FORBIDDEN_FIELDS.includes(k))found.push({type:'field',field:k,path:p}); walk(v[k],p,k);}); return;} if(typeof v==='string'){const low=v.toLowerCase(); FORBIDDEN_WORDS.forEach(w=>{if(low.includes(w.toLowerCase()))found.push({type:'word',word:w,path});});}} walk(value,'',''); return found;}
  function stripRaw(s){const c=JSON.parse(JSON.stringify(s)); delete c.civication._raw; delete c.social._raw; return c;}
  function progressSection(s){const sum=s.progress?.summary||{};const items=[sum.completedTodayLabel||'Fullfør et mål for å se framgang her.'].concat((sum.lastEvents||[]).slice(0,3).map(e=>e.title)).concat(Object.keys(sum.bySource||{}).slice(0,3).map(k=>'Kilde: '+k));return {id:'daily_progress',title:'Dagens framgang',subtitle:sum.hasProgress?'Lokal framgang fra agendaen.':'Fullfør et mål for å se framgang her.',status:sum.hasProgress?'ok':'idle',items,actions:[],warnings:s.progress?.warnings||[],blockers:s.progress?.blockers||[]};}
  function sectionsFrom(s){const mk=(id,title,subtitle,status,items,actions,warnings,blockers)=>({id,title,subtitle,status,items:arr(items),actions:arr(actions),warnings:arr(warnings),blockers:arr(blockers)}); const by=t=>s.actions.filter(a=>a.type===t||a.source===t); return [mk('overview','Oversikt',s.status.summary,s.status.label,[s.status],[],s.warnings,s.blockers),mk('priority','Nå','Agenda og prioriterte forslag','ok',s.objectives?.objectives||s.priority,s.priority,[],[]),progressSection(s),mk('civication','Civication','Jobb, økonomi og bolig',s.civication.available?'ok':'warning',[s.civication],s.actions.filter(a=>['workday','economy','home'].includes(a.type)),s.civication.warnings,s.civication.blockers),mk('learning','Læring','Quiz og domener','ok',[s.learning],by('learning'),s.learning.warnings,[]),mk('social','Folk','Kunnskapsbaserte matcher',s.social.available?'ok':'warning',[s.social],s.actions.filter(a=>['social','profile'].includes(a.type)||a.source==='social'),s.social.warnings,s.social.blockers),mk('routes','Ruter','Foreslåtte ruter',s.routes.available?'ok':'warning',[s.routes],by('routes'),s.routes.warnings,[]),mk('observations','Observasjoner','Trygge observasjonsforslag',s.observations.available?'ok':'warning',[s.observations],by('observations'),s.observations.warnings,[]),mk('diagnostics','Diagnose','Runtime og personvern',s.healthStatus||s.status.label,[s.privacy],s.actions.filter(a=>a.source==='diagnostics'),[],s.blockers)];}
  function objectiveActions(){const ag=call(()=>root.HG_DailyObjectives?.getAgenda?.(),null); return arr(ag?.objectives).filter(o=>['active','suggested','blocked'].includes(o.status)).slice(0,5).map(o=>Object.assign({whyNow:o.reason,safeActionKind:o.actionKind,enabled:o.status!=='blocked'},o,{type:o.type,source:o.source||'daily_objectives'}));}
  function prioritize(actions,blockers){const obj=objectiveActions(); if(obj.length)return obj; const out=[]; if(blockers.length) out.push(action('privacy-or-blockers','diagnostics',blockers.some(b=>/personvern|privacy/i.test(str(b.message||b.key)) )?'Se personvernblokkere':'Se blokkere','Blokkere ligger først i Min dag.',1000,'diagnostics',{actionKind:'open_panel',target:'HG_RuntimeHealthPanel',routeKey:'open_runtime_health'})); return out.concat(actions).sort((a,b)=>b.priority-a.priority).slice(0,7).map(a=>Object.assign({whyNow:a.reason,safeActionKind:a.actionKind},a));}
  async function snapshot(){const runtime=await callAsync(()=>root.HG_RuntimeHealth?.health?.(),null); const civ=collectCivication(); const social=collectSocial(); const learning=collectLearning(social); const routes=collectRoutes(social); const observations=collectObservations(social); let warnings=[...issueList(runtime?.warnings),...civ.warnings,...social.warnings,...learning.warnings,...routes.warnings,...observations.warnings]; let blockers=[...issueList(runtime?.blockers),...civ.blockers,...social.blockers]; const ctx={civication:civ,social,learning,routes,observations}; const actions=buildActions(ctx); let s={version:VERSION,status:null,player:{mode:testMode()?'test_mode':'normal'},civication:civ,workday:{available:!!civ._raw.workday,status:civ.workdayStatus,activeJob:civ.activeJob},economy:{available:!!civ._raw.economy,wallet:civ.wallet,status:civ.economyStatus},home:{available:!!civ._raw.home,status:civ.homeStatus},social,learning,routes,observations,actions,priority:[],sections:[],warnings,blockers,privacy:{ok:true,violations:[],labels:['lokalt','kunnskapsbasert']},timestamp:now(),objectives:call(()=>root.HG_DailyObjectives?.getAgenda?.(),null),progress:call(()=>root.HG_DailyProgress?.getProgress?.(),null)};
    s=stripRaw(s); const pv=scanPrivacy(s); if(pv.length){s.privacy.ok=false; s.privacy.violations=pv; blockers=blockers.concat(pv.map(v=>blocker(`Personvernbrudd i ${v.path||v.field||v.word}`,'today_privacy','privacy'))); s.blockers=blockers;} s.priority=prioritize(s.actions,s.blockers); if(s.progress?.summary?.hasProgress)s.warnings=s.warnings.filter(w=>w.key!=='no_actions'); const score=runtime?.score!=null?num(runtime.score):Math.max(0,100-s.blockers.length*25-s.warnings.length*5); const label=s.privacy.ok===false?'Personvernblokkere':s.blockers.length?'Blokkere':s.warnings.length?'Advarsler':'Klar'; s.status={ok:!s.blockers.length,mode:testMode()?'test_mode':'normal',score,label,summary:label==='Klar'?'Du har en aktiv dag med jobb, læring og sosiale muligheter.':label==='Advarsler'?'Du kan spille videre, men noen systemer har advarsler.':label==='Personvernblokkere'?'Personvernblokkere må fikses før testing.':'Noen blokkere bør fikses før testing.'}; s.sections=sectionsFrom(s); lastSnapshot=s; return s;}
  async function refresh(){lastSnapshot=await snapshot(); return lastSnapshot;}
  async function getActions(){return (await snapshot()).actions;}
  async function getPriorityActions(){return (await snapshot()).priority;}
  async function getSections(){return (await snapshot()).sections;}
  async function health(){const s=await snapshot(); const checks={runtime:{ok:!!root.HG_RuntimeHealth,warnings:root.HG_RuntimeHealth?[]:[warning('Runtime health mangler.','runtime_missing','runtime')]},civication:{ok:s.civication.available},workday:{ok:s.workday.available},economy:{ok:s.economy.available},home:{ok:s.home.available},social:{ok:s.social.available},learning:{ok:true},routes:{ok:true,warnings:s.routes.warnings},observations:{ok:true,warnings:s.observations.warnings},privacy:{ok:s.privacy.ok},panel:{ok:!!root.HG_TodayHubPanel,warnings:root.HG_TodayHubPanel?[]:[warning('Today Hub-panel er ikke lastet.','panel_missing','panel')]},actionRouter:{ok:!!root.HG_TodayActionRouter,warnings:root.HG_TodayActionRouter?[]:[warning('Today action-router mangler.','action_router_missing','today_hub')]},entryPoint:{ok:!!(root.document?.getElementById?.('btnMinDag')),warnings:root.document&&!root.document.getElementById?.('btnMinDag')?[warning('Min dag entry point ikke funnet.','entry_point_missing','today_hub')]:[]}}; const warnings=[...s.warnings,...checks.runtime.warnings,...checks.panel.warnings,...checks.actionRouter.warnings,...checks.entryPoint.warnings]; if(!s.actions.length)warnings.push(warning('Ingen handlinger er tilgjengelige.','no_actions','today_hub')); return {ok:s.blockers.length===0&&s.privacy.ok,score:s.status.score,checks,blockers:s.blockers,warnings,privacyViolations:s.privacy.violations,summary:s.privacy.ok?'Today Hub OK.':'Today Hub har personvernblokkere.',timestamp:now(),objectives:call(()=>root.HG_DailyObjectives?.getAgenda?.(),null),progress:call(()=>root.HG_DailyProgress?.getProgress?.(),null)};}
  async function explain(id){const s=lastSnapshot||await snapshot(); const found=s.actions.find(a=>a.id===id)||s.sections.find(sec=>sec.id===id)||{}; return {id:id||found.id,title:found.title||'Min dag',explanation:'Dette forslaget kommer fra lokale readmodeller for læring, Civication og kunnskapsbasert profil-preview. Det bruker ikke posisjonsdata, sanntidsstatus eller relasjonslister.',source:found.source||found.id||'today_hub',privacyLabels:['lokalt','kunnskapsbasert'],nextSafeStep:found.actionKind==='open_panel'?'Åpne eksisterende read-only panel.':'Les forslaget uten at spillet endres.'};}
  root.HG_TodayHub={snapshot,getSections,getActions,getPriorityActions,health,explain,refresh,_scanPrivacy:scanPrivacy};
}());
