(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis;
  const KEY='hg_public_profile_settings_v1';
  const VERSION=1;
  const SECTION_KEYS=['knowledgeDomains','badges','learnedConcepts','favoritePlaces','routes','quizStrengths','observationTags','signalCount'];
  const FORBIDDEN_FIELDS=new Set(['lat','lng','latitude','longitude','gps','location','liveLocation','presence','isOnline','lastSeen','visitLog','visitedAt','timestampedVisits','followers','followerCount','following','feedTracking']);
  const FORBIDDEN_WORDS=['nearby','distance','GPS','live location','online','last seen','followers','following','feed','avstand','i nærheten','GPS','live-posisjon','pålogget','sist sett','følgere','følger','feed'];
  const ALLOWED_WORD_FIELDS=new Set(['sted','favorittsteder','placeId','favoritePlaces','rute','tema','kunnskapsfelt','kunnskapsspor']);
  const DEFAULTS=Object.freeze({version:VERSION,publicProfileEnabled:false,displayNameMode:'alias',alias:'Historieutforsker',avatarEmoji:'🧭',visibleSections:{knowledgeDomains:true,badges:true,learnedConcepts:true,favoritePlaces:true,routes:true,quizStrengths:true,observationTags:true,signalCount:true},privacyLabels:['Kunnskapsbasert','Ingen GPS','Ingen live-status','Ingen følgere']});
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function storage(){try{return root.localStorage||null;}catch{return null;}}
  function list(v){return Array.isArray(v)?v.filter(x=>x!=null):[];}
  function labels(){try{return root.HG_SocialSurfaceContract?.getLabels?.()?.profile||{};}catch{return {};}}
  function privacyLabelsFromContract(){try{const p=root.HG_SocialSurfaceContract?.getLabels?.()?.privacy||{}; return [p.knowledgeBased,p.noGps,p.noLiveStatus,p.noFollowers].filter(Boolean);}catch{return [];} }
  function sanitizeAlias(v){return String(v==null?DEFAULTS.alias:v).replace(/[<>]/g,'').replace(/\s+/g,' ').trim().slice(0,40)||DEFAULTS.alias;}
  function sanitizeEmoji(v){return String(v==null?DEFAULTS.avatarEmoji:v).trim().slice(0,4)||DEFAULTS.avatarEmoji;}
  function safeExistingName(){try{const n=root.HGProfile?.displayName||root.ProfileIdentity?.displayName; return typeof n==='string'&&n.trim().length>0?n.trim().slice(0,40):null;}catch{return null;}}
  function normalizeVisible(v){const out=clone(DEFAULTS.visibleSections); if(v&&typeof v==='object') SECTION_KEYS.forEach(k=>{ if(Object.prototype.hasOwnProperty.call(v,k)) out[k]=v[k]!==false; }); return out;}
  function normalizeSettings(input){const src=input&&typeof input==='object'?input:{}; const privacy=Array.from(new Set([...DEFAULTS.privacyLabels,...privacyLabelsFromContract(),...list(src.privacyLabels).map(String)])).filter(Boolean); let mode=String(src.displayNameMode||DEFAULTS.displayNameMode); if(mode==='existingProfileName'&&!safeExistingName()) mode='alias'; if(!['alias','anonymous','existingProfileName'].includes(mode)) mode='alias'; return {version:VERSION,publicProfileEnabled:src.publicProfileEnabled===true,displayNameMode:mode,alias:sanitizeAlias(src.alias),avatarEmoji:sanitizeEmoji(src.avatarEmoji),visibleSections:normalizeVisible(src.visibleSections),privacyLabels:privacy};}
  function getSettings(){try{const raw=storage()?.getItem(KEY); return normalizeSettings(raw?JSON.parse(raw):{});}catch{return normalizeSettings({});}}
  function eventPayload(model){return {publicProfileEnabled:!!model.publicProfileEnabled,signalCount:Number(model.counts?.signalCount||model.source?.signalCount||0),visibleSections:clone(model.sections?Object.fromEntries(SECTION_KEYS.map(k=>[k,!!model.sections[k]?.visible])):getSettings().visibleSections)};}
  function dispatch(name,payload){try{root.dispatchEvent?.(new root.CustomEvent(name,{detail:payload}));}catch{}}
  function validate(value){const found=[]; const seen=new WeakSet(); function walk(v,path,key){ if(v&&typeof v==='object'){ if(seen.has(v))return; seen.add(v); Object.keys(v).forEach(k=>{const p=path?`${path}.${k}`:k; if(FORBIDDEN_FIELDS.has(k)) found.push({type:'field',field:k,path:p,value:v[k]}); walk(v[k],p,k);}); return;} if(typeof v==='string'){ if(path.includes('privacyLabels')||path.includes('privacy.labels')||path.includes('privacyChecklist')) return; const last=String(key||path.split('.').pop()||''); if(ALLOWED_WORD_FIELDS.has(last)) return; const low=v.toLowerCase(); FORBIDDEN_WORDS.forEach(w=>{if(low.includes(String(w).toLowerCase())) found.push({type:'word',word:w,path,value:v});}); }} walk(value,'',''); return {publicSafe:found.length===0,forbiddenFieldsFound:found,ok:found.length===0,blockers:found.map(f=>({key:'public_profile_privacy',message:`Public profile privacy blocker at ${f.path}`,details:f}))};}
  function saveSettings(partial){const merged=normalizeSettings({...getSettings(),...(partial||{}),visibleSections:{...getSettings().visibleSections,...((partial||{}).visibleSections||{})}}); const v=validate(merged); if(!v.publicSafe) return {ok:false,error:'privacy_validation_failed',settings:merged,validation:v}; storage()?.setItem(KEY,JSON.stringify(merged)); const model=getReadModel(); dispatch('hg:publicProfileSettingsChanged',eventPayload(model)); return {ok:true,settings:merged,model};}
  function seed(){try{return root.HG_SocialSignals?.getPublicProfileSeed?.()||null;}catch{return null;}}
  function items(v){return list(v).map(x=>typeof x==='object'?clone(x):String(x)).filter(Boolean).slice(0,12);}
  function section(visible,title,itemsValue,emptyLabel){return {visible:!!visible,title,items:items(itemsValue),emptyLabel};}
  function getReadModel(){const settings=getSettings(); const s=seed()||{}; const l=labels(); const sections={knowledgeDomains:section(settings.visibleSections.knowledgeDomains,l.knowledgeFields||'Kunnskapsfelt',s.knowledgeDomains,'Ingen kunnskapsfelt ennå'),badges:section(settings.visibleSections.badges,l.badges||'Merker',s.badges,'Ingen merker ennå'),learnedConcepts:section(settings.visibleSections.learnedConcepts,l.learnedConcepts||'Lærte begreper',s.learnedConcepts,'Ingen lærte begreper ennå'),favoritePlaces:section(settings.visibleSections.favoritePlaces,l.favoritePlaces||'Favorittsteder',s.favoritePlaces,'Ingen favorittsteder ennå'),routes:section(settings.visibleSections.routes,'Ruter',s.routes,'Ingen ruter ennå'),quizStrengths:section(settings.visibleSections.quizStrengths,'Quizstyrker',s.quizStrengths,'Ingen quizstyrker ennå'),observationTags:section(settings.visibleSections.observationTags,'Observasjonstagger',s.observationTags,'Ingen observasjonstagger ennå'),signalCount:section(settings.visibleSections.signalCount,'Signalsammendrag',[`${Number(s.signalCount||0)} signaler`],'Ingen signaler ennå')}; const counts={signalCount:Number(s.signalCount||0),domainCount:list(s.knowledgeDomains).length,badgeCount:list(s.badges).length,conceptCount:list(s.learnedConcepts).length,placeCount:list(s.favoritePlaces).length,routeCount:list(s.routes).length,observationTagCount:list(s.observationTags).length}; const identity={displayName:settings.displayNameMode==='anonymous'?'Anonym historieutforsker':settings.displayNameMode==='existingProfileName'?(safeExistingName()||settings.alias):settings.alias,alias:settings.alias,avatarEmoji:settings.avatarEmoji,demoOnly:false}; const model={version:VERSION,publicProfileEnabled:settings.publicProfileEnabled,identity,sections,counts,privacy:{labels:settings.privacyLabels,forbiddenFieldsFound:[],publicSafe:true},source:{signalsAvailable:!!root.HG_SocialSignals?.getPublicProfileSeed,signalCount:counts.signalCount,generatedFrom:'hg_social_signals_v1'},warnings:[],timestamp:new Date().toISOString()}; const valid=validate(model); model.privacy.forbiddenFieldsFound=valid.forbiddenFieldsFound; model.privacy.publicSafe=valid.publicSafe; if(settings.publicProfileEnabled&&counts.signalCount===0) model.warnings.push({key:'public_profile_enabled_no_signals',message:'Offentlig profil er på, men har ingen signaler ennå.'}); return model;}
  function getPreview(){const m=getReadModel(); const sections=SECTION_KEYS.map(k=>({key:k,...m.sections[k]})); const preview={title:'Offentlig profil',subtitle:m.publicProfileEnabled?'Offentlig profil er på lokalt i denne prototypen.':'Ikke offentlig ennå. Dette er en forhåndsvisning.',enabledLabel:m.publicProfileEnabled?'På':'Av',identityLabel:`${m.identity.avatarEmoji} ${m.identity.displayName}`,sections,privacyChecklist:m.privacy.labels.map(label=>({label,ok:true})),emptyState:m.counts.signalCount?'':'Ingen signaler ennå. Fullfør quiz, ruter eller observasjoner for å fylle profilen.',actions:['toggle_public_profile','edit_alias','choose_sections','refresh_from_signals']}; dispatch('hg:publicProfilePreviewRefreshed',eventPayload(m)); return preview;}
  function health(){const m=getReadModel(); const val=validate(m); const warnings=[...m.warnings]; return {ok:val.publicSafe,summary:val.publicSafe?'Public profile read-model OK.':'Public profile privacy blocker.',blockers:val.blockers,warnings,publicProfileEnabled:m.publicProfileEnabled,signalCount:m.counts.signalCount,storageKey:KEY};}
  function setPublicEnabled(enabled){const result=saveSettings({publicProfileEnabled:enabled===true}); return result.model||getReadModel();}
  function isPublicEnabled(){return getSettings().publicProfileEnabled===true;}
  function clearSettingsForTestMode(){let enabled=false; try{enabled=storage()?.getItem('HG_TEST_MODE')==='1'||root.HG_TEST_MODE==='1';}catch{} if(!enabled)return {ok:true,skipped:true,reason:'test_mode_disabled'}; storage()?.removeItem(KEY); return {ok:true,skipped:false,removed:[KEY]};}
  function getLegacyKnowledgeMatchProfile(){const m=getReadModel(); return {publicProfileEnabled:m.publicProfileEnabled,displayName:m.identity.displayName,avatarEmoji:m.identity.avatarEmoji,knowledgeDomains:m.sections.knowledgeDomains.items,badges:m.sections.badges.items,learnedConcepts:m.sections.learnedConcepts.items,favoritePlaces:m.sections.favoritePlaces.items,privacyLabels:m.privacy.labels,signalCount:m.counts.signalCount};}
  root.HG_PublicProfileReadModel={getSettings,saveSettings,isPublicEnabled,setPublicEnabled,getReadModel,getPreview,validate,health,clearSettingsForTestMode,getLegacyKnowledgeMatchProfile,STORAGE_KEY:KEY};
}());
