(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis;
  const PANEL_ID='hgPublicProfilePreviewPanel';
  const STYLE_ID='hgPublicProfilePreviewPanelStyle';
  function doc(){return root.document;}
  function testMode(){try{return root.localStorage?.getItem('HG_TEST_MODE')==='1'||root.HG_TEST_MODE==='1';}catch{return false;}}
  function escape(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function ensureStyle(){if(doc()?.getElementById?.(STYLE_ID))return; const s=doc()?.createElement?.('style'); if(!s)return; s.id=STYLE_ID; s.textContent=`#${PANEL_ID}{position:fixed;right:16px;top:16px;z-index:2147483646;width:min(420px,calc(100vw - 32px));max-height:calc(100vh - 32px);overflow:auto;background:#fff;color:#111827;border:1px solid #d1d5db;border-radius:14px;box-shadow:0 12px 32px rgba(0,0,0,.24);padding:14px;font:14px/1.4 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#${PANEL_ID} h2{margin:0 0 4px;font-size:18px}#${PANEL_ID} .hg-pp-muted{color:#4b5563}#${PANEL_ID} .hg-pp-grid{display:grid;gap:8px;margin:10px 0}#${PANEL_ID} .hg-pp-card{border:1px solid #e5e7eb;border-radius:10px;padding:8px;background:#f9fafb}#${PANEL_ID} .hg-pp-card h3{font-size:14px;margin:0 0 4px}#${PANEL_ID} button{margin:4px 6px 0 0;border:0;border-radius:8px;padding:7px 9px;background:#111827;color:#fff;font:inherit}#${PANEL_ID} button[data-hg-pp-hide]{background:#6b7280}#${PANEL_ID} button[data-hg-pp-danger]{background:#b91c1c}`; doc().head?.appendChild(s);}
  function panel(){return doc()?.getElementById?.(PANEL_ID)||null;}
  function preview(){return root.HG_PublicProfileReadModel?.getPreview?.()||null;}
  function itemLabel(item){if(item&&typeof item==='object')return item.title||item.label||item.id||JSON.stringify(item); return item;}
  function matchPreview(){try{const g=root.HG_SocialMatchGraph?.buildMatchGraph?.({limit:3}); if(!g)return ''; const names=(g.matches||[]).slice(0,3).map(m=>m.candidate?.displayName).filter(Boolean).join(', '); const reason=g.matches?.[0]?.reasons?.[0]||''; return `<section class="hg-pp-card"><h3>Matcher: ${g.matches?.length||0}</h3><div>${escape(names||'Ingen matcher ennå')}</div><p class="hg-pp-muted">${escape(reason)}</p><button type="button" data-hg-pp-match-graph>Vis match graph</button></section>`;}catch{return '';}}
  function html(p){const sections=(p.sections||[]).filter(s=>s.key!=='signalCount'); return `<h2>${escape(p.title||'Offentlig profil')}</h2><div class="hg-pp-muted">${escape(p.subtitle||'')}</div><p><strong>${escape(p.enabledLabel||'Av')}</strong> · ${escape(p.identityLabel||'')}</p><div>${(p.privacyChecklist||[]).map(x=>`<span aria-label="privacy">✓ ${escape(x.label)}</span>`).join(' · ')}</div>${p.emptyState?`<p class="hg-pp-muted">${escape(p.emptyState)}</p>`:''}<div class="hg-pp-grid">${sections.map(s=>`<section class="hg-pp-card" data-section="${escape(s.key)}"><h3>${escape(s.title)}</h3><div>${(s.items||[]).length?(s.items||[]).map(item=>`<span>${escape(itemLabel(item))}</span>`).join(', '):escape(s.emptyLabel||'Tomt')}</div></section>`).join('')}</div>${matchPreview()}<div><button type="button" data-hg-pp-toggle>Slå offentlig profil av/på</button><button type="button" data-hg-pp-refresh>Oppdater fra signaler</button><button type="button" data-hg-pp-hide>Skjul</button>${testMode()?'<button type="button" data-hg-pp-danger data-hg-pp-clear-settings>Clear profile settings</button><button type="button" data-hg-pp-danger data-hg-pp-clear-signals>Clear social signals</button>':''}</div>`;}
  function bind(el){el.querySelector?.('[data-hg-pp-toggle]')?.addEventListener?.('click',()=>{const api=root.HG_PublicProfileReadModel; api?.setPublicEnabled?.(!api?.isPublicEnabled?.()); refresh();}); el.querySelector?.('[data-hg-pp-refresh]')?.addEventListener?.('click',()=>refresh()); el.querySelector?.('[data-hg-pp-hide]')?.addEventListener?.('click',()=>remove()); el.querySelector?.('[data-hg-pp-match-graph]')?.addEventListener?.('click',()=>root.HG_SocialMatchGraphPanel?.render?.()); el.querySelector?.('[data-hg-pp-clear-settings]')?.addEventListener?.('click',()=>{root.HG_PublicProfileReadModel?.clearSettingsForTestMode?.(); refresh();}); el.querySelector?.('[data-hg-pp-clear-signals]')?.addEventListener?.('click',()=>{root.HG_SocialSignals?.clearSignalsForTestMode?.(); refresh();});}
  function render(mount){if(!doc()||!root.HG_PublicProfileReadModel)return null; ensureStyle(); let el=mount||panel(); if(!el){el=doc().createElement('aside'); el.id=PANEL_ID; el.setAttribute('aria-live','polite'); doc().body?.appendChild(el);} const p=preview(); el.innerHTML=html(p||{}); bind(el); return el;}
  function refresh(){return render(panel());}
  function remove(){panel()?.remove?.(); doc()?.getElementById?.(STYLE_ID)?.remove?.();}
  function isEnabled(){return !!panel();}
  root.HG_PublicProfilePreviewPanel={render,refresh,remove,isEnabled};
}());
