(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis;
  const ACTIONS=['view_profile','send_preset_invite','accept_invite','decline_invite','view_circle','view_shared_route','view_shared_quiz','view_observation','compare_knowledge'];
  const FORBIDDEN_ACTIONS=['free_text_chat','follow_user','show_live_location','show_distance','show_last_seen','show_followers','show_presence'];
  const LABELS=Object.freeze({demoPrefix:'Demo',peopleBlock:{title:'Kunnskapsfolk her',matchOn:'Matcher på',sharedSignals:'Felles signaler',suggestedActivity:'Foreslått aktivitet',sendInvite:'Send invitasjon',sendDemoInvite:'Send demo-invitasjon',inviteSent:'Demo-invitasjon sendt',viewProfile:'Se profil',moreInPanel:'Se flere i demo-panelet',subtitle:'Basert på tema, merker og læringsspor — ikke posisjon.'},inviteStates:{pending:'Venter',incoming:'Innkommende',outgoing:'Sendt',sent:'Sendt',accepted:'Godtatt',declined:'Avslått'},circle:{title:'Krets',members:'Medlemmer',sharedDomains:'Felles tema',activeChallenge:'Aktiv utfordring'},shared:{route:'Felles rute',quiz:'Felles quiz',observation:'Observasjon'},profile:{demoProfile:'Demo-profil',knowledgeFields:'Kunnskapsfelt',badges:'Merker',learnedConcepts:'Lærte begreper',favoritePlaces:'Favorittsteder',sharedActivities:'Felles aktiviteter',privacy:'Personvern',compareKnowledge:'Sammenlign kunnskap',close:'Lukk'},privacy:{knowledgeBased:'Kunnskapsbasert',noGps:'Ingen GPS',noLiveStatus:'Ingen live-status',noFollowers:'Ingen følgere'}});
  const PRIVACY_RULES=Object.freeze([{key:'no_gps',label:'Ingen GPS',severity:'blocker'},{key:'no_live_location',label:'Ingen live-posisjon',severity:'blocker'},{key:'no_presence',label:'Ingen live-status',severity:'blocker'},{key:'no_followers',label:'Ingen følgere',severity:'blocker'},{key:'no_last_seen',label:'Ingen sist sett',severity:'blocker'},{key:'no_free_text_chat',label:'Ingen fritekst-chat',severity:'blocker'},{key:'preset_invites_only',label:'Kun forhåndsvalgte invitasjoner',severity:'blocker'}]);
  const CONTRACT=Object.freeze({surfaces:['placeCard','socialDemoPanel','demoProfile','runtimePanel','futurePublicProfile','futureMinDag'],entities:['person','match','invite','circle','sharedRoute','sharedQuiz','observation','timelineItem'],allowedActions:ACTIONS,forbiddenActions:FORBIDDEN_ACTIONS,demoOnlySurfaces:['placeCard','socialDemoPanel','demoProfile'],readOnly:true});
  const VISIBLE_FORBIDDEN=['nearby','distance','live location','online','last seen','followers','following','feed','avstand','i nærheten','live-posisjon','pålogget','sist sett','følgere','følger'];
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function arr(v){return Array.isArray(v)?v:[];}
  function normalizeAction(a){const s=String(a||'').trim(); return ACTIONS.includes(s)?s:null;}
  function validateSurfaceItem(item){const blockers=[]; if(!item||typeof item!=='object') blockers.push({key:'invalid_item'}); const action=item&&item.action; if(action&&FORBIDDEN_ACTIONS.includes(action)) blockers.push({key:'forbidden_action',action}); if(action&&!ACTIONS.includes(action)) blockers.push({key:'unknown_action',action}); return {ok:blockers.length===0,blockers};}
  function normalizeReason(match={},profile={},context={}){const domains=arr(match.sharedDomains).concat(arr(profile.sharedDomains),arr(profile.knowledgeDomains)).filter(Boolean); const concepts=arr(match.sharedConcepts).concat(arr(profile.learnedConcepts)).filter(Boolean); const badges=arr(profile.badges).filter(Boolean); const text=String(match.reason||'').toLowerCase(); let reason='Begge har sterke signaler i byhistorie og arkitektur.'; if(domains.includes('kunst')||concepts.includes('museum')) reason='Dere deler kunst, museum og observasjon som hovedspor.'; else if(domains.includes('industri')||concepts.includes('industrialisering')) reason='Denne personen passer til ruter med industrihistorie.'; else if(domains.includes('politikk')||concepts.includes('byutvikling')) reason='Felles quizstyrke: politikk og byutvikling.'; else if(domains.includes('by')||concepts.includes('nabolag')||badges.includes('by')) reason='Begge jobber med nabolag, sted og sosial historie.'; else if(text && !scanVisibleText(text).blockers.length && text.length>14) reason=String(match.reason).replace(/[.!?]*$/,'.'); return reason;}
  function scanVisibleText(value){const texts=[]; (function walk(v){ if(v==null)return; if(typeof v==='string') texts.push(v); else if(Array.isArray(v)) v.forEach(walk); else if(typeof v==='object') Object.keys(v).forEach(k=>walk(v[k])); })(value); const blockers=[]; const joined=texts.join('\n'); VISIBLE_FORBIDDEN.forEach(w=>{const re=new RegExp(`(^|[^\\p{L}])${w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^\\p{L}]|$)`,'iu'); if(re.test(joined)) blockers.push({word:w,severity:'blocker'});}); return {ok:blockers.length===0,blockers,warnings:[],forbiddenWords:VISIBLE_FORBIDDEN.slice()};}
  root.HG_SocialSurfaceContract={getContract:()=>clone(CONTRACT),getLabels:()=>clone(LABELS),getActions:()=>({allowed:ACTIONS.slice(),forbidden:FORBIDDEN_ACTIONS.slice()}),getPrivacyRules:()=>clone(PRIVACY_RULES),validateSurfaceItem,normalizeReason,normalizeAction,normalizeMatchReason:normalizeReason,scanVisibleText};
}());
