(function(){
  'use strict';
  const root = typeof window !== 'undefined' ? window : globalThis;
  function tm(){ try { return root.localStorage?.getItem('HG_TEST_MODE') === '1'; } catch { return false; } }
  function snap(){ return root.HG_SocialDemo?.snapshot?.(); }
  function labels(){ return root.HG_SocialSurfaceContract?.getLabels?.() || {}; }
  function isEnabled(){ const s=snap(); return tm() && s?.seeded === true; }
  function clone(v){ return JSON.parse(JSON.stringify(v)); }
  function arr(v){ return Array.isArray(v)?v:[]; }
  function esc(v){ return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function placeObj(placeOrId){ if(placeOrId&&typeof placeOrId==='object') return placeOrId; const id=String(placeOrId||''); return arr(root.PLACES).find(p=>String(p?.id||'')===id) || { id }; }
  function terms(place){ return [place?.category, place?.categoryId, ...(arr(place?.tags)), ...(arr(place?.emne_ids))].map(x=>String(x||'').toLowerCase()).filter(Boolean); }
  function norm(match,u,ctx){ return root.HG_SocialSurfaceContract?.normalizeReason?.(match,u,ctx) || 'Begge har sterke signaler i byhistorie og arkitektur.'; }
  function chips(p){ return arr(p.sharedDomains).concat(arr(p.knowledgeDomains),arr(p.learnedConcepts),arr(p.badges)).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).slice(0,3); }
  function withReason(p, reason, ctx){ return { ...clone(p), reason:norm({reason,sharedDomains:p.sharedDomains},p,ctx), chips:chips(p), suggestedActivity:p.knowledgeDomains?.includes('quiz')?'Felles quiz':'Felles rute', demoOnly:true }; }
  function getPeopleForPlace(placeOrId){ if(!isEnabled()) return []; const pid=String((placeOrId&&typeof placeOrId==='object'?placeOrId.id:placeOrId)||''); const graphMatches=root.HG_SocialMatchGraph?.getMatchesForPlace?.(pid,{limit:8}); if(Array.isArray(graphMatches)&&graphMatches.length) return graphMatches.map(m=>({...clone(m.candidate||{}),userId:m.candidateId,reason:(m.reasons||[])[0],chips:m.sharedDomains||[],suggestedActivity:(m.suggestedActivities||[])[0],demoOnly:true})); const s=snap(); const p=placeObj(placeOrId); const id=String(p?.id||placeOrId||''); const t=terms(p); let people=arr(s.profiles).filter(u=> arr(u.favoritePlaces).includes(id) || arr(s.sharedRoutes).some(r=>arr(r.placeIds).includes(id)&&arr(r.participants).includes(u.userId)) || arr(s.observations).some(o=>o.placeId===id&&arr(o.users).includes(u.userId)) || t.some(term=>arr(u.learnedConcepts).concat(arr(u.sharedDomains),arr(u.knowledgeDomains)).map(x=>String(x).toLowerCase()).includes(term)) ).map(u=>withReason(u,'', {place:p}));
    if(!people.length) people=arr(s.matches).map(m=>{ const u=arr(s.profiles).find(p=>p.userId===m.userId); return u&&withReason(u,m.reason,{place:p}); }).filter(Boolean);
    return people.map(x=>({...x,demoOnly:true})); }
  function getMatchesForPlace(placeId){ return getPeopleForPlace(placeId).map(p=>({ userId:p.userId, displayName:p.displayName, reason:p.reason, sharedDomains:p.sharedDomains||p.knowledgeDomains||[], sharedConcepts:p.learnedConcepts||[], suggestedActivity:p.suggestedActivity, demoOnly:true })); }
  function getInvitesForPlace(placeId){ if(!isEnabled()) return []; return arr(snap().invites).filter(i=>String(i.placeId)===String(placeId)).map(i=>({...clone(i),demoOnly:true})); }
  function getCirclesForPlace(placeId){ if(!isEnabled()) return []; const ids=new Set(getPeopleForPlace(placeId).map(p=>p.userId)); return arr(snap().circles).filter(c=>arr(c.members).some(id=>ids.has(id))).map(c=>({...clone(c),activeChallenge:c.activeChallenge||'Del en kort kildeobservasjon',demoOnly:true})); }
  function getSharedActivitiesForPlace(placeId){ if(!isEnabled()) return []; const s=snap(); return arr(s.sharedRoutes).filter(r=>arr(r.placeIds).includes(String(placeId))).concat(arr(s.sharedQuizzes).filter(q=>q.placeId===String(placeId)), arr(s.observations).filter(o=>o.placeId===String(placeId))).map(x=>({...clone(x),demoOnly:true})); }
  function getProfileById(id){ if(!isEnabled()) return null; const p=arr(snap().profiles).find(p=>p.userId===id); return p?{...clone(p),demoOnly:true}:null; }
  function getPanelSummary(){ const s=snap()||{}; return { enabled:isEnabled(), seeded:s.seeded===true, profileCount:arr(s.profiles).length, matchCount:arr(s.matches).length, inviteCount:arr(s.invites).length, circleCount:arr(s.circles).length, sharedCount:arr(s.sharedRoutes).length+arr(s.sharedQuizzes).length+arr(s.observations).length, privacy:s.privacy||{ok:false}, demoOnly:true }; }
  function renderPlaceSocialBlock(placeOrId){ const all=getPeopleForPlace(placeOrId); const people=all.slice(0,4); const id=String((placeOrId&&typeof placeOrId==='object'?placeOrId.id:placeOrId)||''); const L=labels().peopleBlock||{}; if(!people.length) return ''; const invites=getInvitesForPlace(id); return `<section data-hg-social-demo-block="1" style="margin:10px 0;padding:10px;border:1px dashed #94a3b8;border-radius:10px"><h3 style="margin:0 0 4px;font-size:14px">Demo: ${esc(L.title||'Kunnskapsfolk her')}</h3><p style="margin:0 0 8px;color:#475569">${esc(L.subtitle||'Basert på tema, merker og læringsspor — ikke posisjon.')}</p>${people.map(p=>{const sent=invites.some(i=>i.toUserId===p.userId);return `<article style="margin:8px 0;padding-top:8px;border-top:1px solid #e5e7eb"><strong>${esc(p.avatarEmoji)} ${esc(p.displayName)}</strong> <small>${esc(p.handle)}</small><div>${esc(p.reason)}</div><div>${chips(p).map(c=>`<span style="display:inline-block;margin:2px;padding:2px 6px;border-radius:999px;background:#e0f2fe;color:#075985">${esc(c)}</span>`).join('')}</div><button type="button" data-hg-demo-invite="${esc(p.userId)}" data-hg-demo-place="${esc(id)}" ${sent?'disabled':''}>${sent?'Demo-invitasjon sendt':'Send demo-invitasjon'}</button> <button type="button" data-hg-demo-profile="${esc(p.userId)}">Se profil</button>${sent?' <small>Sendt</small>':''}</article>`;}).join('')}${all.length>4?`<p><small>${esc(L.moreInPanel||'Se flere i demo-panelet')}</small></p>`:''}</section>`; }
  function attachToPlaceCard(card, placeOrId){ if(!card||!isEnabled()) return null; detachFromPlaceCard(card); const html=renderPlaceSocialBlock(placeOrId); if(!html) return null; const wrap=root.document?.createElement?.('div'); if(!wrap) return null; wrap.innerHTML=html; const node=wrap.firstElementChild; if(!node) return null; card.appendChild(node); const pid=String((placeOrId&&typeof placeOrId==='object'?placeOrId.id:placeOrId)||''); node.querySelectorAll('[data-hg-demo-profile]').forEach(b=>b.addEventListener('click',()=>root.HG_SocialDemoProfile?.open?.(b.getAttribute('data-hg-demo-profile'), { placeId:pid }))); node.querySelectorAll('[data-hg-demo-invite]').forEach(b=>b.addEventListener('click',()=>{ const res=root.HG_SocialDemo?.sendDemoInvite?.({toUserId:b.getAttribute('data-hg-demo-invite'), placeId:b.getAttribute('data-hg-demo-place'), presetMessageId:'meet_here', sourceSurface:'placeCard'}); if(res?.ok){ b.textContent='Demo-invitasjon sendt'; b.disabled=true; b.insertAdjacentHTML('afterend',' <small>Sendt</small>'); }})); return node; }
  function detachFromPlaceCard(card){ (card||root.document)?.querySelectorAll?.('[data-hg-social-demo-block="1"]').forEach(n=>n.remove()); }
  root.HG_SocialDemoAdapter = { isEnabled, getPeopleForPlace, getMatchesForPlace, getInvitesForPlace, getCirclesForPlace, getSharedActivitiesForPlace, getProfileById, getPanelSummary, renderPlaceSocialBlock, attachToPlaceCard, detachFromPlaceCard };
}());
