(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis;
  const CACHE_KEY='hg_social_match_graph_cache_v1';
  const FIELDS=['lat','lng','latitude','longitude','gps','location','liveLocation','presence','isOnline','lastSeen','visitLog','visitedAt','timestampedVisits','followers','followerCount','following','feedTracking'];
  const WORDS=['nearby','distance','gps','live location','online','last seen','followers','following','feed','avstand','i nærheten','live-posisjon','pålogget','sist sett','følgere','følger'];
  function tm(){try{return root.localStorage?.getItem('HG_TEST_MODE')==='1'||root.HG_TEST_MODE==='1';}catch{return false;}}
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function arr(v){return Array.isArray(v)?v.filter(x=>x!=null):[];}
  function uniq(v){return Array.from(new Set(arr(v).map(x=>typeof x==='object'?String(x.id||x.routeId||x.placeId||x.title||x.label||JSON.stringify(x)):String(x)).filter(Boolean)));}
  function routes(v){return arr(v).map(r=>typeof r==='object'?{id:String(r.id||r.routeId||r.title||r.theme||''),theme:String(r.theme||r.title||r.id||r.routeId||''),placeIds:uniq(r.placeIds||r.places||r.favoritePlaces)}:{id:String(r),theme:String(r),placeIds:[]}).filter(r=>r.id||r.theme);}
  function section(m,k){return uniq(m?.sections?.[k]?.items||m?.[k]);}
  function normalizeProfile(src,kind,source){src=src||{}; const rm=src.sections?src:null; return {id:String(src.id||src.userId||kind||'candidate'),kind:kind||'candidate',publicProfileEnabled:src.publicProfileEnabled!==false,matchVisibility:src.publicProfileEnabled===false?'preview_only':'local_public_preview',displayName:String(src.displayName||src.identity?.displayName||src.alias||'Historieutforsker').slice(0,60),avatarEmoji:String(src.avatarEmoji||src.identity?.avatarEmoji||'🧭').slice(0,4),knowledgeDomains:section(rm||src,'knowledgeDomains'),badges:section(rm||src,'badges'),learnedConcepts:section(rm||src,'learnedConcepts'),favoritePlaces:section(rm||src,'favoritePlaces'),routes:routes(rm?.sections?.routes?.items||src.routes),quizStrengths:section(rm||src,'quizStrengths'),observationTags:section(rm||src,'observationTags'),signalCount:Number(src.signalCount||src.counts?.signalCount||src.source?.signalCount||0),privacyLabels:uniq(src.privacyLabels||src.privacy?.labels||['Kunnskapsbasert','Ingen GPS','Ingen live-status','Ingen følgere']),demoOnly:src.demoOnly===true,source:source||src.sourceName||null}; }
  function buildSelfProfile(){const m=root.HG_PublicProfileReadModel?.getReadModel?.()||{}; const p=normalizeProfile({...m,id:'self'},'self','public_profile_read_model'); p.id='self'; p.kind='self'; p.demoOnly=false; p.publicProfileEnabled=m.publicProfileEnabled===true; p.matchVisibility=p.publicProfileEnabled?'local_public_preview':'preview_only'; return p;}
  function demoProfiles(){const s=root.HG_SocialDemo?.snapshot?.(); return s?.seeded?arr(s.profiles):[];}
  function getCandidateProfiles(){const candidates=[]; const sources=[]; const warnings=[]; if(tm()){const ps=demoProfiles(); if(ps.length){sources.push({key:'test_mode_demo',count:ps.length}); ps.forEach(p=>candidates.push(normalizeProfile({...p,id:p.userId,publicProfileEnabled:true},'candidate','test_mode_demo')));} else warnings.push('test_mode_demo_not_seeded');}
    if(!tm()){sources.push({key:'backend_not_enabled',count:0}); warnings.push('backend_not_enabled');}
    try{const km=root.HGKnowledgeMatch; const ps=km?.getPublicProfiles?.()||km?.getProfiles?.()||[]; arr(ps).filter(p=>p?.publicProfileEnabled===true&&!p.demoOnly).forEach(p=>candidates.push(normalizeProfile(p,'candidate','hg_knowledge_match'))); if(arr(ps).length) sources.push({key:'hg_knowledge_match',count:arr(ps).length});}catch(e){warnings.push('hg_knowledge_match_unavailable');}
    return {candidates,sources,warnings};}
  function intersect(a,b){const s=new Set(uniq(b).map(x=>x.toLowerCase())); return uniq(a).filter(x=>s.has(x.toLowerCase()));}
  function sharedRoutes(a,b){const br=routes(b.routes); return routes(a.routes).filter(r=>br.some(x=>x.id&&r.id&&x.id===r.id||x.theme&&r.theme&&x.theme.toLowerCase()===r.theme.toLowerCase())).map(r=>r.id||r.theme);}
  function score(parts,self,c){let n=0; n+=Math.min(parts.sharedDomains.length*15,30); n+=Math.min(parts.sharedConcepts.length*8,24); n+=Math.min(parts.sharedBadges.length*10,20); n+=Math.min(parts.sharedRoutes.length*10,20); n+=Math.min(parts.sharedPlaces.length*5,15); n+=Math.min(parts.sharedObservationTags.length*5,15); if(c.publicProfileEnabled)n+=5; if(Number(self.signalCount)>0)n+=5; return Math.max(0,Math.min(100,n));}
  function reasonText(parts,level){const r=[]; if(parts.sharedDomains.length) r.push(`Dere deler ${parts.sharedDomains.slice(0,2).join(' og ')} som sterke kunnskapsspor.`); if(parts.sharedBadges.length) r.push(`Begge har merker innen ${parts.sharedBadges.slice(0,2).join(' og ')}.`); if(parts.sharedConcepts.length) r.push(`Felles begreper peker mot ruter om ${parts.sharedConcepts.slice(0,2).join(' og ')}.`); if(parts.sharedObservationTags.length) r.push(`Begge har observasjonstagger knyttet til ${parts.sharedObservationTags.slice(0,2).join(' og ')}.`); if(!r.length) r.push(level==='weak'?'Denne profilen kan passe til felles quiz.':'Dette er en kunnskapsmatch basert på trygge profilsignaler.'); return r.map(x=>root.HG_SocialSurfaceContract?.normalizeReason?.({reason:x},{},{})||x);}
  function activities(p){const a=['view_profile','compare_knowledge']; if(p.sharedRoutes.length)a.push('shared_route'); if(p.sharedDomains.includes('quiz')||p.sharedBadges.includes('quiz'))a.push('shared_quiz'); a.push('send_preset_invite'); return uniq(a);}
  function makeMatch(self,c){const parts={sharedDomains:intersect(self.knowledgeDomains,c.knowledgeDomains),sharedBadges:intersect(self.badges,c.badges),sharedConcepts:intersect(self.learnedConcepts,c.learnedConcepts),sharedPlaces:intersect(self.favoritePlaces,c.favoritePlaces),sharedRoutes:sharedRoutes(self,c),sharedObservationTags:intersect(self.observationTags,c.observationTags)}; const sc=score(parts,self,c); const level=sc>=70?'strong':sc>=35?'good':'weak'; return {id:`match-${c.id}`,candidateId:c.id,candidate:c,score:sc,level,reasons:reasonText(parts,level),...parts,suggestedActivities:activities(parts),safetyLabels:['local_only','knowledge_based','no_gps','no_presence','no_followers'],source:c.source||'local',demoOnly:c.demoOnly===true};}
  function index(matches,key){const out={}; matches.forEach(m=>arr(m[key]).forEach(v=>{(out[v]||(out[v]=[])).push(m.id);})); return out;}
  function scan(v){const found=[]; const seen=new WeakSet(); (function w(x,p,k){if(x&&typeof x==='object'){if(seen.has(x))return; seen.add(x); Object.keys(x).forEach(n=>{const np=p?`${p}.${n}`:n; if(FIELDS.includes(n))found.push({type:'field',field:n,path:np}); w(x[n],np,n);});} else if(typeof x==='string' && !/privacyLabels|safetyLabels|privacy\./.test(p)){const low=x.toLowerCase(); WORDS.forEach(word=>{if(low.includes(word))found.push({type:'word',word,path:p});});}})(v,'',''); return {ok:found.length===0,blockers:found};}
  function buildMatchGraph(options=/** @type {any} */ ({})){const self=buildSelfProfile(); const got=(/** @type {any} */ (getCandidateProfiles))(options); const matches=got.candidates.map(c=>makeMatch(self,c)).sort((a,b)=>b.score-a.score||a.candidateId.localeCompare(b.candidateId)).slice(0,Number(options?.limit||50)); const graph={self,candidates:got.candidates,matches,placeIndex:index(matches,'sharedPlaces'),domainIndex:index(matches,'sharedDomains'),conceptIndex:index(matches,'sharedConcepts'),generatedFrom:['HG_PublicProfileReadModel'].concat(got.sources.map(s=>s.key)),privacy:{localOnly:true,noBackend:true,noGps:true,noPresence:true,noFollowerMetrics:true},warnings:got.warnings}; const s=scan(graph); if(!s.ok) graph.warnings=graph.warnings.concat(['privacy_scan_blocker']); graph.privacy.scan=s; return graph;}
  function getMatches(o){return buildMatchGraph(o).matches;}
  function placeTerms(placeId){const p=arr(root.PLACES).find(x=>String(x.id)===String(placeId))||{}; return uniq([p.category,p.categoryId,...arr(p.tags),...arr(p.emne_ids)]).map(x=>x.toLowerCase());}
  function routeHasPlace(c,placeId){return routes(c.routes).some(r=>r.placeIds.includes(String(placeId))||r.id===String(placeId));}
  function getMatchesForPlace(placeId,options){const g=buildMatchGraph(options); const terms=placeTerms(placeId); let matches=g.matches.filter(m=>m.sharedPlaces.includes(String(placeId))||m.candidate.favoritePlaces.includes(String(placeId))||routeHasPlace(m.candidate,placeId)||terms.some(t=>m.candidate.knowledgeDomains.concat(m.candidate.observationTags).map(x=>x.toLowerCase()).includes(t))||g.self.favoritePlaces.includes(String(placeId))); if(!matches.length){matches=g.matches.slice(0,3); /** @type {any} */ (matches).warning='generic_knowledge_matches';} return matches;}
  function getMatchReasons(id,o){const m=getMatches(o).find(x=>x.id===id||x.candidateId===id); return m?m.reasons:[];}
  function getSuggestedActivities(id,o){const m=getMatches(o).find(x=>x.id===id||x.candidateId===id); return m?m.suggestedActivities:[];}
  function explainMatch(id,o){const m=getMatches(o).find(x=>x.id===id||x.candidateId===id); return {match:m||null,explanation:'Dette er en kunnskapsmatch, basert på felles domener, begreper, merker og ruter. Den bruker ikke GPS, live-status eller følgere.',factors:m?{domains:m.sharedDomains,concepts:m.sharedConcepts,badges:m.sharedBadges,routes:m.sharedRoutes,places:m.sharedPlaces}: {},privacyLabels:m?.safetyLabels||['local_only','knowledge_based','no_gps','no_presence','no_followers']};}
  function health(){const g=buildMatchGraph({limit:10}); const blockers=[]; const warnings=[...g.warnings]; if(!root.HG_SocialMatchGraph) warnings.push('match_graph_missing'); if(!g.candidates.length&&!tm()) warnings.push('backend_not_enabled'); if(tm()&&demoProfiles().length&&g.matches.length<3) warnings.push('demo_seeded_low_matches'); if(!g.privacy.scan.ok) blockers.push(...g.privacy.scan.blockers); const fake=new Set(demoProfiles().map(p=>p.userId)); const leaked=arr(root.PEOPLE).filter(p=>fake.has(p?.id)||fake.has(p?.userId)); if(leaked.length) blockers.push({key:'demo_users_leaked_global_people',count:leaked.length}); return {ok:blockers.length===0,summary:blockers.length?'Match graph har personvernblokkere.':'Match graph OK.',candidateCount:g.candidates.length,matchCount:g.matches.length,blockers,warnings,privacy:g.privacy};}
  function clearCacheForTestMode(){if(!tm())return {ok:true,skipped:true,reason:'test_mode_disabled'}; root.localStorage?.removeItem(CACHE_KEY); return {ok:true,skipped:false,removed:[CACHE_KEY]};}
  root.HG_SocialMatchGraph={getCandidateProfiles,buildSelfProfile,buildMatchGraph,getMatches,getMatchesForPlace,getMatchReasons,getSuggestedActivities,explainMatch,health,clearCacheForTestMode,CACHE_KEY,_scanPrivacy:scan};
}());
