(function(){
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis; const ID='hgSocialDemoProfile';
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function enabled(){try{return root.localStorage?.getItem('HG_TEST_MODE')==='1'&&root.HG_SocialDemo?.snapshot?.().seeded===true;}catch{return false;}}
  function arr(v){return Array.isArray(v)?v:[];} function list(v){return arr(v).map(esc).join(' · ')||'—';}
  function sharedActivities(profile){const s=root.HG_SocialDemo?.snapshot?.()||{}; return arr(s.sharedRoutes).filter(r=>arr(r.participants).includes(profile.userId)).length+' ruter · '+arr(s.sharedQuizzes).filter(q=>arr(q.participants).includes(profile.userId)).length+' quiz · '+arr(s.observations).filter(o=>arr(o.users).includes(profile.userId)).length+' observasjoner';}
  function compareHtml(profile){const c=root.HG_SocialDemo?.compareKnowledge?.(profile.userId)||{domains:[],concepts:[],badges:[]}; return `<div data-hg-demo-compare-result="1"><p><b>Felles tema:</b> ${list(c.domains)}</p><p><b>Felles begreper:</b> ${list(c.concepts)}</p><p><b>Felles merker:</b> ${list(c.badges)}</p></div>`;}
  function renderCard(profile, opts={}){ if(!enabled()||!profile) return ''; return `<div data-hg-demo-profile-card="1" data-demo-only="true"><div style="font-size:28px">${esc(profile.avatarEmoji)}</div><h2>${esc(profile.displayName)}</h2><strong>Demo-profil</strong><p>${esc(profile.handle||'')}</p><p>${esc(profile.bio||'')}</p><p><b>Kunnskapsfelt:</b> ${list(profile.knowledgeDomains)}</p><p><b>Merker:</b> ${list(profile.badges)}</p><p><b>Lærte begreper:</b> ${list(profile.learnedConcepts)}</p><p><b>Favorittsteder:</b> ${list(profile.favoritePlaces)}</p><p><b>Felles aktiviteter:</b> ${esc(sharedActivities(profile))}</p><p><b>Personvern</b></p><ul><li>Ingen GPS</li><li>Ingen live-status</li><li>Ingen følgere</li></ul><div data-hg-demo-compare-slot></div><button type="button" data-hg-demo-profile-invite="${esc(profile.userId)}" data-hg-demo-place="${esc(opts.placeId||profile.favoritePlaces?.[0]||'demo-place')}">Send demo-invitasjon</button> <button type="button" data-hg-demo-compare="${esc(profile.userId)}">Sammenlign kunnskap</button> <button type="button" data-hg-demo-profile-close>Lukk</button></div>`; }
  function close(){ root.document?.getElementById(ID)?.remove(); }
  function open(userId, opts={}){ if(!enabled()) return null; const p=root.HG_SocialDemoAdapter?.getProfileById?.(userId); if(!p) return null; root.HG_SocialDemo?.logDemoAction?.('profile_opened',{toUserId:userId}); close(); const el=root.document.createElement('div'); el.id=ID; el.style.cssText='position:fixed;inset:0;z-index:2147483647;background:rgba(0,0,0,.35);display:grid;place-items:center'; el.innerHTML=`<section style="max-width:420px;background:white;color:#111;padding:16px;border-radius:14px;box-shadow:0 16px 48px rgba(0,0,0,.35)">${renderCard(p,opts)}</section>`; el.querySelector('[data-hg-demo-profile-close]')?.addEventListener('click',close); el.querySelector('[data-hg-demo-compare]')?.addEventListener('click',()=>{ const slot=el.querySelector('[data-hg-demo-compare-slot]'); if(slot) slot.innerHTML=compareHtml(p); }); el.querySelector('[data-hg-demo-profile-invite]')?.addEventListener('click',(ev)=>{ const b=ev.currentTarget; const res=root.HG_SocialDemo?.sendDemoInvite?.({toUserId:b.getAttribute('data-hg-demo-profile-invite'),placeId:b.getAttribute('data-hg-demo-place'),presetMessageId:'meet_here',sourceSurface:'demoProfile'}); if(res?.ok){b.textContent='Demo-invitasjon sendt';b.disabled=true;} }); root.document.body?.appendChild(el); return el; }
  root.HG_SocialDemoProfile={open,close,renderCard,compareKnowledge:(id)=>root.HG_SocialDemo?.compareKnowledge?.(id)};
}());
