(function(){
'use strict'; const root=typeof window!=='undefined'?window:globalThis; const ID='hgSocialDemoPanel';
function tm(){try{return root.localStorage?.getItem('HG_TEST_MODE')==='1';}catch{return false;}} function arr(v){return Array.isArray(v)?v:[];} function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));} function remove(){root.document?.getElementById(ID)?.remove();}
function render(){ if(!tm()) return null; remove(); root.HG_SocialDemo?.logDemoAction?.('panel_opened'); const s=root.HG_SocialDemo?.snapshot?.()||{}; const sum=root.HG_SocialDemoAdapter?.getPanelSummary?.()||{}; const L=root.HG_SocialSurfaceContract?.getLabels?.()||{}; const rules=root.HG_SocialSurfaceContract?.getPrivacyRules?.()||[]; const el=root.document.createElement('aside'); el.id=ID; el.style.cssText='position:fixed;left:12px;bottom:12px;z-index:2147483646;width:min(720px,calc(100vw - 24px));max-height:86vh;overflow:auto;background:#111827;color:white;border-radius:12px;padding:14px;font:13px system-ui;box-shadow:0 18px 54px rgba(0,0,0,.35)';
const stateLabel=x=>(L.inviteStates||{})[x]||x; const profiles=arr(s.profiles); const matches=arr(s.matches).slice(0,8).map(m=>{const p=profiles.find(x=>x.userId===m.userId)||{}; const reason=root.HG_SocialSurfaceContract?.normalizeReason?.(m,p)||m.reason; return `<li><b>${esc(p.displayName||m.userId)}</b><br>${esc(reason)}<br><small>${esc(arr(p.sharedDomains).concat(arr(p.learnedConcepts)).slice(0,4).join(' · '))}</small><br><small>${esc((L.peopleBlock||{}).suggestedActivity||'Foreslått aktivitet')}: ${esc(p.knowledgeDomains?.includes('quiz')?'Felles quiz':'Felles rute')}</small><br><button data-invite="${esc(m.userId)}">Send demo-invitasjon</button></li>`;}).join('');
const invGroups=['incoming','outgoing','sent','accepted','declined','pending'].map(st=>`<h4>${esc(stateLabel(st))}</h4><ul>${arr(s.invites).filter(i=>(i.status||'pending')===st).map(i=>`<li>${esc(i.toUserId)} — ${esc(i.presetLabel||i.presetMessageId)}</li>`).join('')||'<li>Ingen</li>'}</ul>`).join('');
el.innerHTML=`<h2>HG Social demo</h2><button data-seed>Seed demo</button> <button data-reset>Reset demo</button> <button data-health>Social health</button> <button data-smoke>Smoke</button> <button data-close>Lukk</button><section><h3>Oversikt</h3><p>${sum.profileCount||profiles.length} profiler · ${sum.matchCount||arr(s.matches).length} matcher · ${sum.inviteCount||arr(s.invites).length} invitasjoner · ${sum.circleCount||arr(s.circles).length} kretser · ${sum.sharedCount||0} felles aktiviteter</p><p>${esc((L.privacy||{}).knowledgeBased||'Kunnskapsbasert')}: ${s.privacy?.ok!==false?'OK':'Sjekk'}</p></section><section><h3>Profiler</h3><ul>${profiles.map(p=>`<li>${esc(p.avatarEmoji)} ${esc(p.displayName)} ${esc(p.handle)}</li>`).join('')}</ul></section><section><h3>Matcher</h3><ul>${matches}</ul></section><section><h3>Invitasjoner</h3>${invGroups}<p><small>Kun forhåndsvalgte invitasjoner. Ingen fritekst.</small></p></section><section><h3>Kretser</h3><ul>${arr(s.circles).map(c=>`<li><b>${esc(c.title||'Krets')}</b><br>Medlemmer: ${esc(arr(c.members).join(' · '))}<br>Felles tema: ${esc(arr(c.focusDomains).join(' · '))}<br>Aktiv utfordring: ${esc(c.activeChallenge||'Del en kort kildeobservasjon')}</li>`).join('')}</ul></section><section><h3>Felles aktiviteter</h3><p>Felles rute: ${arr(s.sharedRoutes).length} · Felles quiz: ${arr(s.sharedQuizzes).length} · Observasjon: ${arr(s.observations).length}</p></section><section><h3>Tidslinje</h3><ul>${arr(s.timeline).map(t=>`<li>${esc(t.type||t.eventId)}</li>`).join('')}</ul></section><section><h3>Personvern</h3><ul>${rules.map(r=>`<li>✓ ${esc(r.label)}</li>`).join('')}</ul></section>`;
el.querySelector('[data-seed]')?.addEventListener('click',()=>{root.HG_SocialDemo?.seed?.({resetFirst:true}); render();}); el.querySelector('[data-reset]')?.addEventListener('click',()=>{root.HG_SocialDemo?.reset?.(); root.HG_SocialDemo?.clearActions?.(); render();}); el.querySelector('[data-close]')?.addEventListener('click',remove); el.querySelector('[data-health]')?.addEventListener('click',()=>root.HG_SocialDebug?.health?.()); el.querySelector('[data-smoke]')?.addEventListener('click',()=>root.HG_RuntimeSmokeRunner?.run?.()); el.querySelectorAll('[data-invite]').forEach(b=>b.addEventListener('click',()=>{const res=root.HG_SocialDemo?.sendDemoInvite?.({toUserId:b.getAttribute('data-invite'),placeId:'demo-panel',presetMessageId:'meet_here',sourceSurface:'demoPanel'}); if(res?.ok){b.textContent='Demo-invitasjon sendt';b.disabled=true;}})); root.document.body?.appendChild(el); return el; }
root.HG_SocialDemoPanel={render,remove,isEnabled:tm};
}());
